/** @file

Copyright (c) 2020, Intel Corporation. All rights reserved.<BR>
SPDX-License-Identifier: BSD-2-Clause-Patent

  This file is automatically generated. Please do NOT modify !!!

**/

#ifndef __FSPUPD_H__
#define __FSPUPD_H__

#include <FspEas.h>

#pragma pack(1)

#define FSPT_UPD_SIGNATURE               0x545F4450554C4845        /* 'EHLUPD_T' */

#define FSPM_UPD_SIGNATURE               0x4D5F4450554C4845        /* 'EHLUPD_M' */

#define FSPS_UPD_SIGNATURE               0x535F4450554C4845        /* 'EHLUPD_S' */

#pragma pack()

#endif
