/** @file
Defines Platform BoardIds

  Copyright (c) 2020 - 2025, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent

  This file is automatically generated. Please do NOT modify !!!

**/

#ifndef _PLATFORM_BOARD_ID_H_
#define _PLATFORM_BOARD_ID_H_

#define FlavorMobile                        0x1
#define FlavorDesktop                       0x2

// AlderLake-N Boards
#define BoardIdAdlNDdr5Crb                            0x0B // MiniITX is CRB
#define PLATFORM_ID_ADL_N_DDR5_CRB                    0x0A

#define BoardIdAdlNUp7000EdgeN50                      0x06
#define PLATFORM_ID_ADL_N_UP7EN50                     0x06

#define BoardIdAdlNUp2ProTWL                          0x1E
#define PLATFORM_ID_ADL_N_UP2PTWL                     0x1E

#define BoardIdAdlNLp5Rvp                             0x07
#define PLATFORM_ID_ADL_N_LPDDR5_RVP                  0x07

// Added for ADL-PS Board IDs
#define BoardIdAdlPSDdr5Rvp                           0x0B
#define PLATFORM_ID_ADL_PS_DDR5_RVP                   0x0B

#define BoardIdAdlPSDdr5Crb                           0x0D // MiniITX is CRB
#define PLATFORM_ID_ADL_PS_DDR5_CRB                   0x0D

// AlderLake P Board IDs
#define BoardIdAdlPLp4Rvp                             0x10
#define PLATFORM_ID_ADL_P_LP4_RVP                     0x10

#define BoardIdAdlPDdr5Rvp                            0x12
#define PLATFORM_ID_ADL_P_DDR5_RVP                    0x12

#define BoardIdAdlPLp5Rvp                             0x13
#define PLATFORM_ID_ADL_P_LP5_RVP                     0x13

#define BoardIdAdlpUpXtremei12                        0x04
#define PLATFORM_ID_ADL_P_UPXI12                      0x04

#define PLATFORM_ID_RPL_P_UPXI12                      0x14

// AlderLake-S & ADP-S Boards
#define BoardIdAdlSAdpSDdr4UDimm2DCrb                 0x27
#define PLATFORM_ID_ADL_S_ADP_S_CRB                   0x17

#define BoardIdAdlSAdpSDdr4SODimmCrb                  0x35
#define PLATFORM_ID_ADL_S_ADP_S_DDR4_SODIMM_CRB       0x18

#define BoardIdAdlSAdpSDdr5UDimm1DCrb                 0x2B
#define PLATFORM_ID_ADL_S_ADP_S_DDR5_UDIMM_1DC_CRB    0x1B

#define BoardIdAdlSAdpSDdr5SODimmCrb                  0x30
#define PLATFORM_ID_ADL_S_ADP_S_DDR5_SODIMM_CRB       0x1C

// ArizonaBeach Boards
#define BoardIdAzbLp5Crb2A                            0x22
#define PLATFORM_ID_AZB_LP5_CRB2A                     0x09

// Test boards
#define BoardIdTestSDdr5UDimm1DRvp                    0x39
#define PLATFORM_ID_TEST_S_DDR5_UDIMM_RVP             0x19

#define BoardIdTestSDdr5SODimmRvp                     0x31  // S17
#define PLATFORM_ID_TEST_S_DDR5_SODIMM_RVP            0x11

#define BoardIdRplPDdr5Rvp                            0x17
#define BoardIdRplPLp5Rvp                             0x05

#define PLATFORM_ID_RPL_P_DDR5_CRB                    0x08

#define BoardIdRplPRki                                0x1F  // Rock Island
#define PLATFORM_ID_RPL_P_RKI                         0x1F  // Rock Island

// RPL-P Auto Malibou Lake Boards
#define BoardIdRplPLp5AutoRvp                         0x05  // Standard 6 bits Board ID used when reading from IO Expander
#define ExtendedBoardIdRplPLp5AutoRvp                 0x45  // MBL RVP Platform ID when read from FRU EEPROM
#define BoardIdRplPAutoLp5Crb                         0x46  // MBL CRB Platform ID when read from FRU EEPROM

#define PLATFORM_ID_RPLP_LP5_AUTO_RVP                 0x05  // Internal Platform Id for Malibou Lake RVP Fab. A and B.
#define PLATFORM_ID_RPLP_LP5_AUTO_CRB                 0x15  // Internal Platform Id for Malibou Lake CRB.
#define FabIdRplPLp5AutoRvpRev1                       0x01  // FAB-B Revision ID

#define DisplayIdRplpAutoDualDp                       0x0
#define DisplayIdRplpAutoDualMipi                     (BIT0 | BIT1)

#endif // _PLATFORM_BOARD_ID_H_
