/** @file
Defines Platform BoardIds

  Copyright (c) 2020 - 2022, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent

  This file is automatically generated. Please do NOT modify !!!

**/

#ifndef _PLATFORM_BOARD_ID_H_
#define _PLATFORM_BOARD_ID_H_

#define FlavorMobile                        0x1
#define FlavorDesktop                       0x2

// AlderLake-N Boards
#define BoardIdAdlNDdr5Crb                            0x0A // MiniITX is CRB
#define PLATFORM_ID_ADL_N_DDR5_CRB                    0x0A

#define BoardIdAdlNLp5Rvp                             0x07
#define PLATFORM_ID_ADL_N_LPDDR5_RVP                  0x07

// Added for ADL-PS Board IDs
#define BoardIdAdlPSDdr5Rvp                           0x0B
#define PLATFORM_ID_ADL_PS_DDR5_RVP                   0x0B

#define BoardIdAdlPSDdr5Crb                           0x0D // MiniITX is CRB
#define PLATFORM_ID_ADL_PS_DDR5_CRB                   0x0D

// AlderLake P Board IDs
#define BoardIdAdlPLp4Rvp                             0x10
#define PLATFORM_ID_ADL_P_LP4_RVP                     0x10

#define BoardIdAdlPDdr5Rvp                            0x12
#define PLATFORM_ID_ADL_P_DDR5_RVP                    0x12

#define BoardIdAdlPLp5Rvp                             0x13
#define PLATFORM_ID_ADL_P_LP5_RVP                     0x13

// AlderLake-S & ADP-S Boards
#define BoardIdAdlSAdpSDdr4UDimm2DCrb                 0x27
#define PLATFORM_ID_ADL_S_ADP_S_CRB                   0x17

#define BoardIdAdlSAdpSDdr4SODimmCrb                  0x35
#define PLATFORM_ID_ADL_S_ADP_S_DDR4_SODIMM_CRB       0x18

#define BoardIdAdlSAdpSDdr5UDimm1DCrb                 0x2B
#define PLATFORM_ID_ADL_S_ADP_S_DDR5_UDIMM_1DC_CRB    0x1B

#define BoardIdAdlSAdpSDdr5SODimmCrb                  0x30
#define PLATFORM_ID_ADL_S_ADP_S_DDR5_SODIMM_CRB       0x1C

// Test boards
#define BoardIdTestSDdr5UDimm1DRvp                    0x39
#define PLATFORM_ID_TEST_S_DDR5_UDIMM_RVP             0x19

#define BoardIdTestSDdr5SODimmRvp                     0x31  // S17
#define PLATFORM_ID_TEST_S_DDR5_SODIMM_RVP            0x11

#endif // _PLATFORM_BOARD_ID_H_
