/** @file
  Device IDs for PCH Serial IO Controllers for CNL PCH

  Copyright (c) 2018 - 2019, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent

**/
#ifndef _PCH_REGS_SERIAL_IO_CNL_
#define _PCH_REGS_SERIAL_IO_CNL_

#define PCI_DEVICE_NUMBER_PCH_SERIAL_IO_I2C0            21
#define PCI_FUNCTION_NUMBER_PCH_SERIAL_IO_I2C0          0

#define V_CNL_PCH_LP_SERIAL_IO_CFG_I2C0_DEVICE_ID       0x9DE8
#define V_CNL_PCH_H_SERIAL_IO_CFG_I2C0_DEVICE_ID        0xA368
#define V_CML_PCH_LP_SERIAL_IO_CFG_I2C0_DEVICE_ID       0x02E8
#define V_CML_PCH_H_SERIAL_IO_CFG_I2C0_DEVICE_ID        0x06E8

//
//  Serial IO I2C1 Controller Registers
//
#define PCI_DEVICE_NUMBER_PCH_SERIAL_IO_I2C1            21
#define PCI_FUNCTION_NUMBER_PCH_SERIAL_IO_I2C1          1

#define V_CNL_PCH_LP_SERIAL_IO_CFG_I2C1_DEVICE_ID       0x9DE9
#define V_CNL_PCH_H_SERIAL_IO_CFG_I2C1_DEVICE_ID        0xA369
#define V_CML_PCH_LP_SERIAL_IO_CFG_I2C1_DEVICE_ID       0x02E9
#define V_CML_PCH_H_SERIAL_IO_CFG_I2C1_DEVICE_ID        0x06E9

//
//  Serial IO I2C2 Controller Registers
//
#define PCI_DEVICE_NUMBER_PCH_SERIAL_IO_I2C2            21
#define PCI_FUNCTION_NUMBER_PCH_SERIAL_IO_I2C2          2

#define V_CNL_PCH_LP_SERIAL_IO_CFG_I2C2_DEVICE_ID       0x9DEA
#define V_CNL_PCH_H_SERIAL_IO_CFG_I2C2_DEVICE_ID        0xA36A
#define V_CML_PCH_LP_SERIAL_IO_CFG_I2C2_DEVICE_ID       0x02EA
#define V_CML_PCH_H_SERIAL_IO_CFG_I2C2_DEVICE_ID        0x06EA

//
//  Serial IO I2C3 Controller Registers
//
#define PCI_DEVICE_NUMBER_PCH_SERIAL_IO_I2C3            21
#define PCI_FUNCTION_NUMBER_PCH_SERIAL_IO_I2C3          3

#define V_CNL_PCH_LP_SERIAL_IO_CFG_I2C3_DEVICE_ID       0x9DEB
#define V_CNL_PCH_H_SERIAL_IO_CFG_I2C3_DEVICE_ID        0xA36B
#define V_CML_PCH_LP_SERIAL_IO_CFG_I2C3_DEVICE_ID       0x02EB
#define V_CML_PCH_H_SERIAL_IO_CFG_I2C3_DEVICE_ID        0x06EB

//
//  Serial IO I2C4 Controller Registers
//
#define PCI_DEVICE_NUMBER_PCH_SERIAL_IO_I2C4            25
#define PCI_FUNCTION_NUMBER_PCH_SERIAL_IO_I2C4          0

#define V_CNL_PCH_LP_SERIAL_IO_CFG_I2C4_DEVICE_ID       0x9DC5
#define V_CML_PCH_LP_SERIAL_IO_CFG_I2C4_DEVICE_ID       0x02C5

//
//  Serial IO I2C5 Controller Registers
//
#define PCI_DEVICE_NUMBER_PCH_SERIAL_IO_I2C5            25
#define PCI_FUNCTION_NUMBER_PCH_SERIAL_IO_I2C5          1

#define V_CNL_PCH_LP_SERIAL_IO_CFG_I2C5_DEVICE_ID       0x9DC6
#define V_CML_PCH_LP_SERIAL_IO_CFG_I2C5_DEVICE_ID       0x02C6

//
//  Serial IO SPI0 Controller Registers
//
#define PCI_DEVICE_NUMBER_PCH_SERIAL_IO_SPI0            30
#define PCI_FUNCTION_NUMBER_PCH_SERIAL_IO_SPI0          2

#define V_CNL_PCH_LP_SERIAL_IO_CFG_SPI0_DEVICE_ID       0x9DAA
#define V_CNL_PCH_H_SERIAL_IO_CFG_SPI0_DEVICE_ID        0xA32A
#define V_CML_PCH_LP_SERIAL_IO_CFG_SPI0_DEVICE_ID       0x02AA
#define V_CML_PCH_H_SERIAL_IO_CFG_SPI0_DEVICE_ID        0x06AA

//
//  Serial IO SPI1 Controller Registers
//
#define PCI_DEVICE_NUMBER_PCH_SERIAL_IO_SPI1            30
#define PCI_FUNCTION_NUMBER_PCH_SERIAL_IO_SPI1          3

#define V_CNL_PCH_LP_SERIAL_IO_CFG_SPI1_DEVICE_ID       0x9DAB
#define V_CNL_PCH_H_SERIAL_IO_CFG_SPI1_DEVICE_ID        0xA32B
#define V_CML_PCH_LP_SERIAL_IO_CFG_SPI1_DEVICE_ID       0x02AB
#define V_CML_PCH_H_SERIAL_IO_CFG_SPI1_DEVICE_ID        0x06AB

//
//  Serial IO SPI2 Controller Registers
//
#define PCI_DEVICE_NUMBER_PCH_SERIAL_IO_SPI2            18
#define PCI_FUNCTION_NUMBER_PCH_SERIAL_IO_SPI2          6

#define V_CNL_PCH_LP_SERIAL_IO_CFG_SPI2_DEVICE_ID       0x9DFB
#define V_CNL_PCH_H_SERIAL_IO_CFG_SPI2_DEVICE_ID        0xA37B
#define V_CML_PCH_LP_SERIAL_IO_CFG_SPI2_DEVICE_ID       0x02FB
#define V_CML_PCH_H_SERIAL_IO_CFG_SPI2_DEVICE_ID        0x06FB

//
//  Serial IO UART0 Controller Registers
//
#define PCI_DEVICE_NUMBER_PCH_SERIAL_IO_UART0           30
#define PCI_FUNCTION_NUMBER_PCH_SERIAL_IO_UART0         0

#define V_CNL_PCH_LP_SERIAL_IO_CFG_UART0_DEVICE_ID      0x9DA8
#define V_CNL_PCH_H_SERIAL_IO_CFG_UART0_DEVICE_ID       0xA328
#define V_CML_PCH_LP_SERIAL_IO_CFG_UART0_DEVICE_ID      0x02A8
#define V_CML_PCH_H_SERIAL_IO_CFG_UART0_DEVICE_ID       0x06A8

//
//  Serial IO UART1 Controller Registers
//
#define PCI_DEVICE_NUMBER_PCH_SERIAL_IO_UART1           30
#define PCI_FUNCTION_NUMBER_PCH_SERIAL_IO_UART1         1

#define V_CNL_PCH_LP_SERIAL_IO_CFG_UART1_DEVICE_ID      0x9DA9
#define V_CNL_PCH_H_SERIAL_IO_CFG_UART1_DEVICE_ID       0xA329
#define V_CML_PCH_LP_SERIAL_IO_CFG_UART1_DEVICE_ID      0x02A9
#define V_CML_PCH_H_SERIAL_IO_CFG_UART1_DEVICE_ID       0x06A9

//
//  Serial IO UART2 Controller Registers
//
#define PCI_DEVICE_NUMBER_PCH_SERIAL_IO_UART2           25
#define PCI_FUNCTION_NUMBER_PCH_SERIAL_IO_UART2         2

#define V_CNL_PCH_LP_SERIAL_IO_CFG_UART2_DEVICE_ID      0x9DC7
#define V_CNL_PCH_H_SERIAL_IO_CFG_UART2_DEVICE_ID       0xA347
#define V_CML_PCH_LP_SERIAL_IO_CFG_UART2_DEVICE_ID      0x02C7
#define V_CML_PCH_H_SERIAL_IO_CFG_UART2_DEVICE_ID       0x06C7

#endif
