/** @file
Defines Platform BoardIds

  Copyright (c) 2020 - 2024, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent

  This file is automatically generated. Please do NOT modify !!!

**/

#ifndef _PLATFORM_BOARD_ID_H_
#define _PLATFORM_BOARD_ID_H_

#define FlavorMobile                        0x1
#define FlavorDesktop                       0x2
#define FlavorMobileWorkstation             0x6


#define TypeUnknown                         0x0
#define TypeTrad                            0x1
#define TypeUltUlx                          0x2


#define MtlSimicsSkuType 1

#define BoardIdReserved                  0x00

// MTL P Board Id's
#define BoardIdMtlPDdr5SODimmSbsErb           0x0D
#define BoardIdMtlPDdr5SODimmSbsRvp           0x01
#define PLATFORM_ID_MTL_P_DDR5_RVP            0x01

  #define BomIdMtlPDdr5SODimmSbsRvpBom        0x01
  #define BomIdMtlPDdr5SODimmSbsPpvRvp        0x02
  #define BomIdMtlPDdr5SODimmSbsChromeRvp     0x03

#define BoardIdMtlPLp5xT3Rvp                  0x02
#define PLATFORM_ID_MTL_P_LPDDR5_T3_RVP       0x02
#define BoardIdMtlPDdr5SODimmB2bHsioRvp       0x03
#define BoardIdMtlPLp5xT4Rvp                  0x04
  #define BomIdMtlPLp5xT4ChromeRvp            0x01

#define BoardIdMtlPDdr5MemSolderDowndTBTRvp   0x05

// MTL M Board Id's
#define BoardIdMtlMLp5xConf1Erb               0x0E
#define BoardIdMtlMLp5xConf1Rvp               0x06
  #define BomIdMtlMLp5xConf1Rvpbom            0x01
  #define BomIdMtlMLp5xConf1PpvRvp            0x02
  #define BomIdMtlMLp5xConf1ChromeRvp         0x03

#define BoardIdMtlMLp5xConf2Rvp               0x07
#define BoardIdMtlMLp5xPmicRvp                0x08

#define BoardIdUnknown1                       0xffff

// MTL PS Board Id's
#define BoardIdMtlPSDdr5Rvp                   0x14
#define PLATFORM_ID_MTL_PS_DDR5_RVP           0x14
#define BoardIdMtlPSDdr5Crb                   0x15
#define PLATFORM_ID_MTL_PS_DDR5_CRB           0x15
#define BoardIdMtlPDdr5CRb                    0x1A
#define PLATFORM_ID_MTL_P_DDR5_CRB            0x1A
#define BoardIdMtlPDdr5Mcl                    0x1F
#define PLATFORM_ID_MTL_P_DDR5_MCL            0x1F
/** MTL backup
#define TypeUnknown                         0x0
#define TypeTrad                            0x1
#define TypeUltUlx                          0x2


// BoardId Reserved for PCD Default SkuId usage
#define BoardIdReserved                     0x00

// MTL P Board Id's
#define BoardIdMtlPDdr5SODimmSbsErb           0x0D
#define BoardIdMtlPDdr5SODimmSbsRvp           0x01
#define PLATFORM_ID_MTL_P_DDR5_RVP            0x01

  #define BomIdMtlPDdr5SODimmSbsRvpBom        0x01
  #define BomIdMtlPDdr5SODimmSbsPpvRvp        0x02
  #define BomIdMtlPDdr5SODimmSbsChromeRvp     0x03

#define BoardIdMtlPLp5xT3Rvp                  0x02
#define BoardIdMtlPDdr5SODimmB2bHsioRvp       0x03
#define BoardIdMtlPLp5xT4Rvp                  0x04
  #define BomIdMtlPLp5xT4ChromeRvp            0x01

#define BoardIdMtlPDdr5MemSolderDowndTBTRvp   0x05

// MTL M Board Id's
#define BoardIdMtlMLp5xConf1Erb               0x0E
#define BoardIdMtlMLp5xConf1Rvp               0x06
  #define BomIdMtlMLp5xConf1Rvpbom            0x01
  #define BomIdMtlMLp5xConf1PpvRvp            0x02
  #define BomIdMtlMLp5xConf1ChromeRvp         0x03

#define BoardIdMtlMLp5xConf2Rvp               0x07
#define BoardIdMtlMLp5xPmicRvp                0x08


#define BoardIdUnknown1                     0xffff
 **/


#endif // _PLATFORM_BOARD_ID_H_
