//
// Automatically generated by GenNvs ver 2.4.7
// Please DO NOT modify !!!
//

/**@file

  Copyright (c) 2026, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent
**/

  //
  // Define IPU NVS Area operation region.
  //


  OperationRegion(IPNV,SystemMemory,IPNB,IPNL)
  Field(IPNV,AnyAcc,Lock,Preserve)
  {
  IPTP, 8,  // Offset(0),     IPU ACPI device type (0=Disabled, 1=AVStream virtual device as child of GFX)
  }