/** @file
Defines Platform BoardIds

  Copyright (c) 2026, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent

  This file is automatically generated. Please do NOT modify !!!

**/

#ifndef _PLATFORM_BOARD_ID_H_
#define _PLATFORM_BOARD_ID_H_

#define FlavorMobile                        0x1
#define FlavorDesktop                       0x2
#define FlavorMobileWorkstation             0x6

#define TypeUnknown                         0x0
#define TypeTrad                            0x1
#define TypeUltUlx                          0x2

#define PtlSimicsSkuType                     1

#define BoardIdReserved                      0x00

// PTL P Board Id's

#define BoardIdPtlUHLp5Rvp1                      0x01
#define PLATFORM_ID_PTL_UH_LP5X_T3_RVP           0x01

#define BoardIdPtlUHLp5T4MemSktRvp               0x03
#define PLATFORM_ID_PTL_UH_LP5X_T4_RVP           0x03

#define BoardIdPtlUHDdr5Rvp4                     0x04
#define PLATFORM_ID_PTL_UH_DDR5_T3_RVP           0x04

#define BoardIdPtlUHDdr5EmbCrb                   0x32
#define PLATFORM_ID_PTL_UH_DDR5_EMB_CRB          0x05

#define BoardIdPtlUHLp5Robinson                  0x0A
#define PLATFORM_ID_PTL_UH_LP5X_Robinson         0x0A

// WCL Board Id's
#define BoardIdWclDdr5Crb                        0x35
#define PLATFORM_ID_WCL_DDR5_CRB                 0x06

#define BoardIdWclLp5Rvp                         0x21
#define PLATFORM_ID_WCL_LP5X_RVP                 0x07

#define BoardIdWclDdr5Rvp                        0x20
#define PLATFORM_ID_WCL_DDR5_RVP                 0x08

#define BoardIdSimicsRvp                        0x31

#define BoardIdUnknown1                         0xff
#define PLATFORM_ID_UNKNOWN_RVP                 0xff

#endif // _PLATFORM_BOARD_ID_H_
