/** @file
  ACPI Pep devices override method defintions.

  Copyright (c) 2026, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

//
// CondRefOf check for the device is safe because the SSDTs are
// always initialized after DSDT. And all the devices is defined
// in DSDT.
//
#define PEP_DEVICE_OVERRIDE(Device, PepNvs, PepNvsMax) \
        If (CondRefOf (ROOT_COMPLEX.Device)) { \
          Scope (ROOT_COMPLEX.Device) { \
            Method (POVR, 1, Serialized) { \
              ADBG (#Device) \
              ADBG (Concatenate ("PEP default value: ", ToHexString (Arg0))) \
              ADBG (Concatenate ("PEP override value: ", ToHexString (PepNvs))) \
              If (LAnd (LNotEqual (Arg0, 0), LNotEqual (PepNvs, 0))) { \
                If (LGreater (PepNvsMax, 1)) { \
                  If (LEqual (Arg0, 5)) { \
                    Return (Arg0) \
                  } \
                  Return (PepNvs) \
                } \
                Return (Arg0) \
              } Else { \
                Return (0) \
              } \
            } \
          } \
        }

#define DEVICE_OVERRIDE_REQUIRED_EXTERNAL(Device) \
        External (ROOT_COMPLEX.Device, DeviceObj)

DEVICE_OVERRIDE_REQUIRED_EXTERNAL (GFX0)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (UA00)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (UA01)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (UA02)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (I2C0)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (I2C1)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (I2C2)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (I2C3)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (I2C4)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (I2C5)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (I2C6)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (I2C7)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (SPI0)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (SPI1)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (SPI2)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (XHCI)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (HDAS)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (CNVW)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (BTPC)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (IPU0)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (NPU0)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (GNA0)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (VMD0)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (HECI)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (HEC3)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (GLAN)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (THC0)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (THC1)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (ISHD)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (PUF0)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (PUF1)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (PEMC)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (SAT0)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (OSE0)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (OSE1)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (ESE0)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (SAT0.PRT0)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (SAT0.PRT1)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (SAT0.PRT2)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (SAT0.PRT3)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (SAT0.PRT4)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (SAT0.PRT5)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (SAT0.PRT6)
DEVICE_OVERRIDE_REQUIRED_EXTERNAL (SAT0.PRT7)

//
// Pep devices constraint override method definitions.
// Arguments (DeviceName, PepNvs, MaxPepValue)
//
// Note: MaxPepValue  - 1: support 0/1 - Disable/Enable
//                    - 3: support 0/1/3 - Disable/D0F1/D3
//
PEP_DEVICE_OVERRIDE (GFX0, PTGX, 1)
PEP_DEVICE_OVERRIDE (UA00, PTUT, 1)
PEP_DEVICE_OVERRIDE (UA01, PTUT, 1)
PEP_DEVICE_OVERRIDE (UA02, PTUT, 1)
PEP_DEVICE_OVERRIDE (I2C0, PT20, 1)
PEP_DEVICE_OVERRIDE (I2C1, PT21, 1)
PEP_DEVICE_OVERRIDE (I2C2, PT22, 1)
PEP_DEVICE_OVERRIDE (I2C3, PT23, 1)
PEP_DEVICE_OVERRIDE (I2C4, PT24, 1)
PEP_DEVICE_OVERRIDE (I2C5, PT25, 1)
PEP_DEVICE_OVERRIDE (I2C6, PT26, 1)
PEP_DEVICE_OVERRIDE (I2C7, PT27, 1)
PEP_DEVICE_OVERRIDE (SPI0, PTSI, 1)
PEP_DEVICE_OVERRIDE (SPI1, PTSI, 1)
PEP_DEVICE_OVERRIDE (SPI2, PTSI, 1)
PEP_DEVICE_OVERRIDE (XHCI, PTXI, 1)
PEP_DEVICE_OVERRIDE (HDAS, PTAO, 3)
// PEP_DEVICE_OVERRIDE (CNVW, XXXX, 1)
// PEP_DEVICE_OVERRIDE (BTPC, XXXX, 1)
PEP_DEVICE_OVERRIDE (IPU0, PTIU, 1)
PEP_DEVICE_OVERRIDE (NPU0, PTVU, 1)
PEP_DEVICE_OVERRIDE (GNA0, PTGN, 1)
PEP_DEVICE_OVERRIDE (VMD0, PTVM, 1)
PEP_DEVICE_OVERRIDE (HECI, PTCE, 1)
PEP_DEVICE_OVERRIDE (HEC3, PTH3, 1)
PEP_DEVICE_OVERRIDE (GLAN, PTGE, 1)
PEP_DEVICE_OVERRIDE (THC0, PTT0, 1)
PEP_DEVICE_OVERRIDE (THC1, PTT1, 1)
PEP_DEVICE_OVERRIDE (PUF0, PTU0, 1)
PEP_DEVICE_OVERRIDE (PUF1, PTU1, 1)
PEP_DEVICE_OVERRIDE (PEMC, PTEM, 1)
PEP_DEVICE_OVERRIDE (SAT0, PTSA, 3)
PEP_DEVICE_OVERRIDE (ISHD, PTIH, 1)
PEP_DEVICE_OVERRIDE (OSE0, POSE, 1)
PEP_DEVICE_OVERRIDE (OSE1, POSE, 1)
PEP_DEVICE_OVERRIDE (ESE0, PESE, 1)
PEP_DEVICE_OVERRIDE (SAT0.PRT0, PTSE, 1)
PEP_DEVICE_OVERRIDE (SAT0.PRT1, PTSE, 1)
PEP_DEVICE_OVERRIDE (SAT0.PRT2, PTSE, 1)
PEP_DEVICE_OVERRIDE (SAT0.PRT3, PTSE, 1)
PEP_DEVICE_OVERRIDE (SAT0.PRT4, PTSE, 1)
PEP_DEVICE_OVERRIDE (SAT0.PRT5, PTSE, 1)
PEP_DEVICE_OVERRIDE (SAT0.PRT6, PTSE, 1)
PEP_DEVICE_OVERRIDE (SAT0.PRT7, PTSE, 1)
