#!/usr/bin/env python
## @file
#  Generate FSP UPD per-board delta blobs for embedding in CFGDATA tags.
#
#  This script produces one delta blob per board per FSP phase.
#  Each blob is a self-contained payload suitable for injection
#  into a CFGDATA tag.
#
#  The delta baseline is derived from YAML defaults (CfgDataDef.yaml +
#  the CfgData_FspM.yaml / CfgData_FspS.yaml files generated by
#  GenFspUpdYaml.py).  Because GenFspUpdYaml.py extracts those defaults
#  byte-exactly from the FSP binary CfgRegion, the produced delta blob
#  is bit-identical to what an FSP-binary-based generator would emit.
#  No FSP binary or FspXUpd.h header is required at delta-gen time.
#
#  Tag assignment:  tag = base_tag + PlatformId
#    FSP-M base: CDATA_FSPM_DELTA_BASE_TAG (0x500 = FSPM UPD CFGDATA tag)
#    FSP-S base: CDATA_FSPS_DELTA_BASE_TAG (0x520 = FSPS UPD CFGDATA tag)
#
#  Blob layout (per-board, no header):
#    [Delta entries - packed]    (Offset:2 + Length:1 + Value[Length]) x N
#    [Padding to DWORD align]
#
#  Copyright (c) 2026, Intel Corporation. All rights reserved.<BR>
#  SPDX-License-Identifier: BSD-2-Clause-Patent
#
##

import os
import re
import sys
import struct
import argparse
import subprocess
import tempfile

# CFGDATA tag base IDs - same as the UPD defaults tags (must match ConfigDataLib.c)
CDATA_FSPM_DELTA_BASE_TAG = 0x500
CDATA_FSPS_DELTA_BASE_TAG = 0x520


def gen_board_cfgdata_bin(dlt_file, pkl_file, output_bin, gen_cfg_data_tool):
    """Use GenCfgData.py to generate a per-board CFGDATA binary."""
    cmd = [sys.executable, gen_cfg_data_tool, 'GENBIN',
           '%s;%s' % (pkl_file, dlt_file), output_bin]
    ret = subprocess.call(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    if ret != 0:
        raise RuntimeError(f"GenCfgData GENBIN failed for {dlt_file}")


def extract_tag_data_from_cfgdata_bin(cfgdata_bin_path, tag_id):
    """Extract raw payload for a given tag from a CFGDATA binary blob."""
    with open(cfgdata_bin_path, 'rb') as f:
        data = f.read()

    if data[0:4] != b'CFGD':
        raise ValueError(f"Invalid CFGDATA signature in {cfgdata_bin_path}")
    header_len  = data[4]
    used_length = struct.unpack_from('<I', data, 8)[0]

    offset = header_len
    while offset < used_length:
        word0 = struct.unpack_from('<I', data, offset)[0]
        cond_num   = word0 & 0x3
        length_dw  = (word0 >> 2) & 0x7FF
        tag        = (word0 >> 20) & 0xFFF

        entry_len_bytes = length_dw * 4
        if entry_len_bytes == 0:
            break

        hdr_size       = 4 + (cond_num * 4)
        payload_offset = offset + hdr_size
        payload_size   = entry_len_bytes - hdr_size

        if tag == tag_id and payload_size > 0:
            return bytearray(data[payload_offset:payload_offset + payload_size])

        offset += entry_len_bytes

    return None


def compute_deltas(base_data, board_data):
    """Compare base vs board bytes and produce delta entries.

    Consecutive differing bytes are merged into single entries.
    Returns list of (offset, length, value_bytes).
    """
    assert len(base_data) == len(board_data)
    deltas = []
    size = len(base_data)
    i = 0
    while i < size:
        if base_data[i] != board_data[i]:
            start = i
            while i < size and base_data[i] != board_data[i]:
                i += 1
            run_len = i - start
            while run_len > 0:
                chunk = min(run_len, 255)
                value = bytes(board_data[start:start + chunk])
                deltas.append((start, chunk, value))
                start += chunk
                run_len -= chunk
        else:
            i += 1
    return deltas


def parse_dlt_platform_id(dlt_file):
    """Extract PlatformId from a DLT file."""
    with open(dlt_file, 'r') as f:
        for line in f:
            line = line.strip()
            if line.startswith('#') or '|' not in line:
                continue
            if 'PLATFORMID_CFG_DATA.PlatformId' in line:
                parts = line.split('|')
                return int(parts[1].strip(), 0)
    return None


def build_per_board_blob(deltas):
    """Build a per-board delta blob (packed entries only, no header).

    Layout:
        [delta entries - packed]  Offset(2B) + Length(1B) + Value[Length]
        [padding to DWORD align]
    """
    output = bytearray()
    for offset, length, value in deltas:
        output += struct.pack('<HB', offset, length)
        output += value
    # DWORD-align
    while len(output) % 4 != 0:
        output += b'\x00'
    return output


# ---------------------------------------------------------------
# YAML-only path (no FSP binary / no FspXUpd.h required)
# ---------------------------------------------------------------
_CFG_BASE_RE_FSPM = re.compile(r'^\s*#\s*@fspm_cfg_base\s*:\s*(0x[0-9A-Fa-f]+|\d+)',
                                re.MULTILINE)
_CFG_BASE_RE_FSPS = re.compile(r'^\s*#\s*@fsps_cfg_base\s*:\s*(0x[0-9A-Fa-f]+|\d+)',
                                re.MULTILINE)


def preserve_fsp_upd_base_markers(src_cfg_dir, flat_yaml_path):
    """Copy '@fspm_cfg_base' / '@fsps_cfg_base' comment markers from the
    per-FSP source yamls into the flattened top-level yaml.

    GenCfgData.py GENYML flattens '!include' files by data merge, which
    drops YAML comments (including the markers stitch-time delta
    regeneration needs).  Read the markers from CfgData_FspM.yaml /
    CfgData_FspS.yaml in the source cfg dir and prepend them to the
    flattened yaml so a bundled Outputs/*/CfgDataDef.yaml is self-
    sufficient for GenFspUpdDelta._read_cfg_bases().

    No-op when either the flattened yaml is missing, the per-FSP source
    yamls are absent, or the markers are already present in the
    flattened yaml.
    """
    if not os.path.exists(flat_yaml_path):
        return
    markers = []
    seen = set()
    for src_name, cre, key in (
            ('CfgData_FspM.yaml', _CFG_BASE_RE_FSPM, 'fspm'),
            ('CfgData_FspS.yaml', _CFG_BASE_RE_FSPS, 'fsps')):
        src_path = os.path.join(src_cfg_dir, src_name)
        if not os.path.exists(src_path):
            continue
        try:
            with open(src_path, 'r') as f:
                text = f.read()
        except Exception:
            continue
        m = cre.search(text)
        if m and key not in seen:
            seen.add(key)
            markers.append('#  @%s_cfg_base: 0x%X\n' %
                           (key, int(m.group(1), 0)))
    if not markers:
        return
    with open(flat_yaml_path, 'r') as f:
        flat_text = f.read()
    if _CFG_BASE_RE_FSPM.search(flat_text) and \
       _CFG_BASE_RE_FSPS.search(flat_text):
        return
    header = ('#  FSP UPD cfg-base markers propagated by BuildUtility '
              'from per-FSP source yamls (see GenFspUpdYaml.py).\n')
    with open(flat_yaml_path, 'w') as f:
        f.write(header + ''.join(markers) + flat_text)


def _read_cfg_bases(cfg_dir):
    """Locate the '@fspm_cfg_base' / '@fsps_cfg_base' markers.

    GenFspUpdYaml.py emits these YAML comments in CfgData_FspM.yaml and
    CfgData_FspS.yaml.  In an Outputs bundle those files may have been
    flattened into a single top-level CfgDataDef*.yaml via '!include'
    expansion, so we scan the known files first and fall back to any
    *.yaml in cfg_dir.

    Returns:
        (fspm_cfg_base, fsps_cfg_base) as ints, either may be None.
    """
    import glob as _glob
    fspm_cfg_base = None
    fsps_cfg_base = None
    preferred = ('CfgData_FspM.yaml', 'CfgData_FspS.yaml', 'CfgDataDef.yaml')
    fallback  = sorted(os.path.basename(p)
                       for p in _glob.glob(os.path.join(cfg_dir, '*.yaml')))
    seen = set()
    for name in list(preferred) + fallback:
        if name in seen:
            continue
        seen.add(name)
        path = os.path.join(cfg_dir, name)
        if not os.path.exists(path):
            continue
        try:
            with open(path, 'r') as f:
                text = f.read()
        except Exception:
            continue
        if fspm_cfg_base is None:
            m = _CFG_BASE_RE_FSPM.search(text)
            if m:
                fspm_cfg_base = int(m.group(1), 0)
        if fsps_cfg_base is None:
            m = _CFG_BASE_RE_FSPS.search(text)
            if m:
                fsps_cfg_base = int(m.group(1), 0)
        if fspm_cfg_base is not None and fsps_cfg_base is not None:
            break
    return fspm_cfg_base, fsps_cfg_base


def _ensure_pkl(yaml_or_pkl, out_dir, gen_cfg_data_tool):
    """Return a usable pkl path for yaml_or_pkl, generating one if needed."""
    if yaml_or_pkl.endswith('.pkl'):
        return yaml_or_pkl
    pkl_file = os.path.join(out_dir, 'CfgDataDef.pkl')
    if not os.path.exists(pkl_file):
        cmd = [sys.executable, gen_cfg_data_tool, 'GENPKL',
               yaml_or_pkl, pkl_file]
        ret = subprocess.call(cmd, stdout=subprocess.DEVNULL,
                              stderr=subprocess.DEVNULL)
        if ret != 0:
            raise RuntimeError("Failed to generate pkl from %s" % yaml_or_pkl)
    return pkl_file


def _gen_defaults_cfgdata_bin(pkl_file, out_bin, gen_cfg_data_tool):
    """Produce a CFGDATA binary populated with YAML defaults only (no dlt)."""
    cmd = [sys.executable, gen_cfg_data_tool, 'GENBIN', pkl_file, out_bin]
    ret = subprocess.call(cmd, stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL)
    if ret != 0:
        raise RuntimeError("GenCfgData GENBIN (defaults) failed for %s"
                           % pkl_file)


def gen_fsp_upd_delta_blobs(cfg_dir, output_dir, dlt_files,
                             yaml_file, gen_cfg_data_tool):
    """Generate per-board FSP UPD delta blobs using YAML defaults.

    No FSP binary or FSP header is required.  The YAML defaults are
    byte-identical to the FSP binary defaults by construction (see
    GenFspUpdYaml.py), so the resulting delta blob is bit-exact to what
    an FSP-binary-based generator would emit.

    Args:
        cfg_dir:           Directory containing CfgDataDef.yaml (with
                           the '@fspm_cfg_base' / '@fsps_cfg_base'
                           markers propagated by BuildUtility).
        output_dir:        Where to write FspmDelta_0xNNN.bin / FspsDelta_*.bin.
        dlt_files:         Iterable of per-board .dlt file paths.
        yaml_file:         Path to CfgDataDef.yaml (or .pkl).
        gen_cfg_data_tool: Full path to GenCfgData.py.

    Returns:
        list of (platform_id, fspm_tag, fspm_size, fsps_tag, fsps_size,
                 fspm_path, fsps_path).
    """
    fspm_cfg_base, fsps_cfg_base = _read_cfg_bases(cfg_dir)
    if fspm_cfg_base is None or fsps_cfg_base is None:
        raise RuntimeError(
            "Missing '@fspm_cfg_base' / '@fsps_cfg_base' comment marker "
            "in %s/CfgData_Fsp{M,S}.yaml (or CfgDataDef.yaml).  "
            "Regenerate cfg data with a build that writes the marker."
            % cfg_dir)
    fspm_upd_tag = CDATA_FSPM_DELTA_BASE_TAG
    fsps_upd_tag = CDATA_FSPS_DELTA_BASE_TAG
    print("  FSP UPD cfg_base: fspm=0x%X fsps=0x%X" %
          (fspm_cfg_base, fsps_cfg_base))

    pkl_file = _ensure_pkl(yaml_file, output_dir, gen_cfg_data_tool)
    with tempfile.TemporaryDirectory() as tmpdir:
        defaults_bin = os.path.join(tmpdir, 'CfgDataDefaults.bin')
        _gen_defaults_cfgdata_bin(pkl_file, defaults_bin, gen_cfg_data_tool)

        default_fspm = extract_tag_data_from_cfgdata_bin(defaults_bin,
                                                        fspm_upd_tag)
        default_fsps = extract_tag_data_from_cfgdata_bin(defaults_bin,
                                                        fsps_upd_tag)
        if default_fspm is None or default_fsps is None:
            raise RuntimeError("YAML-generated defaults bin %s missing "
                               "FSPM/FSPS UPD tag payload" % defaults_bin)

        results = []
        for dlt_file in dlt_files:
            dlt_name    = os.path.basename(dlt_file)
            platform_id = parse_dlt_platform_id(dlt_file)
            if platform_id is None:
                print("  WARNING: No PlatformId in %s, skipping" % dlt_name)
                continue
            if not (0 <= platform_id < 32):
                # tag = base + platform_id and CondValue = 1 << platform_id
                # both require 0..31.  Out-of-range would silently produce a
                # wildcard CondValue at inject time, applying the delta to
                # every board.
                print("  WARNING: PlatformId 0x%02X in %s out of range "
                      "[0..31], skipping" % (platform_id, dlt_name))
                continue
            print("  Board PlatformId=0x%02X (%s)" % (platform_id, dlt_name))

            board_bin = os.path.join(tmpdir,
                                     os.path.splitext(dlt_name)[0] + '.bin')
            try:
                gen_board_cfgdata_bin(dlt_file, pkl_file, board_bin,
                                      gen_cfg_data_tool)
            except RuntimeError as e:
                print("    WARNING: %s -- skipping" % e)
                continue

            m_deltas = _delta_entries_from_payloads(
                default_fspm,
                extract_tag_data_from_cfgdata_bin(board_bin, fspm_upd_tag),
                fspm_cfg_base)
            print("    FSP-M: %d delta entries" % len(m_deltas))
            fspm_blob = build_per_board_blob(m_deltas)
            fspm_tag  = CDATA_FSPM_DELTA_BASE_TAG + platform_id
            fspm_path = os.path.join(output_dir,
                                     'FspmDelta_0x%03X.bin' % fspm_tag)
            with open(fspm_path, 'wb') as f:
                f.write(fspm_blob)

            s_deltas = _delta_entries_from_payloads(
                default_fsps,
                extract_tag_data_from_cfgdata_bin(board_bin, fsps_upd_tag),
                fsps_cfg_base)
            print("    FSP-S: %d delta entries" % len(s_deltas))
            fsps_blob = build_per_board_blob(s_deltas)
            fsps_tag  = CDATA_FSPS_DELTA_BASE_TAG + platform_id
            fsps_path = os.path.join(output_dir,
                                     'FspsDelta_0x%03X.bin' % fsps_tag)
            with open(fsps_path, 'wb') as f:
                f.write(fsps_blob)

            results.append((platform_id, fspm_tag, len(fspm_blob),
                            fsps_tag, len(fsps_blob), fspm_path, fsps_path))
            print("    Tags: 0x%03X (%dB), 0x%03X (%dB)" %
                  (fspm_tag, len(fspm_blob), fsps_tag, len(fsps_blob)))

    print("\nGenerated %d boards, %d delta blobs in %s" %
          (len(results), len(results) * 2, output_dir))
    return results


def _delta_entries_from_payloads(default_payload, board_payload, cfg_base):
    """Diff two CFGDATA tag payloads and emit UPD-relative delta entries.

    default_payload and board_payload are the raw bytes stored under the
    FSPM_UPD_CFG_DATA / FSPS_UPD_CFG_DATA tag (config fields only, no
    outer header).  The tag payload byte 0 corresponds to full-UPD byte
    'cfg_base', so we add cfg_base to each entry's offset before emit.
    Fails fast on a length mismatch: silently truncating would drop
    tail differences and mask real drift between defaults and per-board
    binaries.
    """
    if default_payload is None or board_payload is None:
        return []
    if len(default_payload) != len(board_payload):
        raise RuntimeError(
            "FSP UPD payload length mismatch: defaults=%d board=%d" %
            (len(default_payload), len(board_payload)))
    entries = compute_deltas(default_payload, board_payload)
    return [(off + cfg_base, ln, val) for (off, ln, val) in entries]


def inject_delta_tags_into_cfgdata(bin_file, delta_blobs):
    """Inject per-board FSP UPD delta blobs as CDATA tags into CFGDATA.bin.

    This is the common implementation used by BuildLoader.py after delta
    blob generation.  It can also be invoked via the --inject CLI flag.

    Args:
        bin_file:     Path to CFGDATA.bin to patch in-place.
        delta_blobs:  List of (tag_id, blob_bytes) tuples.
    """
    data = bytearray(open(bin_file, 'rb').read())
    if len(data) < 16 or data[:4] != b'CFGD':
        raise Exception('Invalid CFGDATA.bin: bad signature')

    hdr_len = data[4]
    used    = int.from_bytes(data[8:12], 'little')
    total   = int.from_bytes(data[12:16], 'little')

    for tag, blob in delta_blobs:
        if blob is None:
            continue
        # DWORD-align payload
        payload = bytearray(blob)
        while len(payload) % 4 != 0:
            payload.append(0)

        # CDATA_HEADER (4 bytes) + CDATA_COND (4 bytes) + payload
        # Length field = total size in DWORDs (header + cond + payload)
        cond_num = 1
        tag_total_bytes = 4 + 4 * cond_num + len(payload)
        length_dwords = tag_total_bytes // 4

        # word0: ConditionNum[1:0] | Length[12:2] | Flags[15:13] | Version[19:16] | Tag[31:20]
        word0 = (cond_num & 0x3) | ((length_dwords & 0x7FF) << 2) | ((tag & 0xFFF) << 20)
        # Delta tags are 1:1 with PID (tag = base + PID), so encode that
        # PID's bit in CondValue rather than a wildcard mask.
        if CDATA_FSPM_DELTA_BASE_TAG <= tag < CDATA_FSPM_DELTA_BASE_TAG + 32:
            cond_val = 1 << (tag - CDATA_FSPM_DELTA_BASE_TAG)
        elif CDATA_FSPS_DELTA_BASE_TAG <= tag < CDATA_FSPS_DELTA_BASE_TAG + 32:
            cond_val = 1 << (tag - CDATA_FSPS_DELTA_BASE_TAG)
        else:
            cond_val = 0xFFFFFFFF

        tag_data = word0.to_bytes(4, 'little') + cond_val.to_bytes(4, 'little') + payload
        # Insert into the used area
        insert_off = used
        data[insert_off:insert_off+len(tag_data)] = tag_data
        used += len(tag_data)
        print('Injected CDATA tag 0x%03X: %d bytes payload, total tag %d bytes at offset 0x%X' %
              (tag, len(blob), len(tag_data), insert_off))

    if used > total:
        # Grow TotalLength to accommodate the injected data
        total = used

    # Update UsedLength and TotalLength
    data[8:12]  = used.to_bytes(4, 'little')
    data[12:16] = total.to_bytes(4, 'little')
    open(bin_file, 'wb').write(data)
    print('Updated CfgData UsedLength=0x%X TotalLength=0x%X' % (used, total))


def collect_delta_blobs(delta_dir):
    """Scan delta_dir for generated FspXDelta_0xNNN.bin files.

    Returns:
        List of (tag_id, blob_bytes) tuples sorted by filename.
    """
    import glob as _glob
    delta_blobs = []
    for delta_file in sorted(_glob.glob(os.path.join(delta_dir, 'Fsp*Delta_0x*.bin'))):
        tag_str = os.path.splitext(os.path.basename(delta_file))[0].split('_0x')[-1]
        tag_id = int(tag_str, 16)
        blob = open(delta_file, 'rb').read()
        delta_blobs.append((tag_id, blob))
    return delta_blobs


def gen_and_inject_fsp_upd_deltas(fv_dir, brd_cfg_dir, cfg_bin_path,
                                  dlt_files=None, cfg_dir=None,
                                  gen_cfg_data_tool=None):
    """Generate FSP UPD per-board delta blobs and inject into CFGDATA.

    Always regenerates delta blobs from YAML defaults and the supplied
    per-board DLT files.  This is safe at both build time and stitch
    time because GenFspUpdYaml.py extracts YAML defaults byte-exactly
    from the FSP binary CfgRegion, so a YAML-derived delta is bit-
    identical to an FSP-derived one for the same DLT.

    Args:
        fv_dir:            Working directory for intermediate files and
                           where the delta blobs are written.
        brd_cfg_dir:       Board CfgData source directory containing DLT
                           files.
        cfg_bin_path:      Path to the unsigned merged CFGDATA binary to
                           patch.
        dlt_files:         Optional list of DLT filenames (resolved in
                           fv_dir first, then brd_cfg_dir).  When None,
                           all DLT files in brd_cfg_dir are scanned.
        cfg_dir:           Directory containing CfgDataDef.yaml with the
                           '@fspm_cfg_base' / '@fsps_cfg_base' markers
                           propagated by BuildUtility.  Defaults to
                           brd_cfg_dir.
        gen_cfg_data_tool: Full path to GenCfgData.py.  When None, falls
                           back to the default full-build relative path.
    """
    import glob as _glob
    import shutil

    if cfg_dir is None:
        cfg_dir = brd_cfg_dir
    if gen_cfg_data_tool is None:
        gen_cfg_data_tool = os.path.join('BootloaderCorePkg', 'Tools',
                                         'GenCfgData.py')

    delta_dir = os.path.join(fv_dir, 'FspUpdDeltas')

    # Prefer the pkl if it exists; otherwise the yaml.
    pkl_file  = os.path.join(fv_dir, 'CfgDataDef.pkl')
    yaml_file = os.path.join(cfg_dir, 'CfgDataDef.yaml')
    if os.path.exists(pkl_file):
        cfg_input = pkl_file
    elif os.path.exists(yaml_file):
        cfg_input = yaml_file
    else:
        # Nothing to base the delta on; skip silently.
        return

    if dlt_files is not None:
        # Resolve provided filenames: check fv_dir first, then brd_cfg_dir
        dlt_paths = []
        for name in dlt_files:
            p = os.path.join(fv_dir, name)
            if not os.path.exists(p):
                p = os.path.join(brd_cfg_dir, name)
            if os.path.exists(p):
                try:
                    content = open(p, 'r').read()
                except Exception:
                    continue
                if 'FSPM_UPD_CFG_DATA' in content or \
                   'FSPS_UPD_CFG_DATA' in content:
                    dlt_paths.append(p)
    else:
        # Auto-discover DLT files containing FSP UPD overrides
        dlt_paths = []
        for dlt_file in sorted(_glob.glob(os.path.join(brd_cfg_dir, '*.dlt'))):
            try:
                content = open(dlt_file, 'r').read()
            except Exception:
                continue
            if 'FSPM_UPD_CFG_DATA' in content or \
               'FSPS_UPD_CFG_DATA' in content:
                dlt_paths.append(dlt_file)

    if not dlt_paths:
        return

    print('  Found %d DLT files with FSP UPD overrides' % len(dlt_paths))

    # Clean stale delta files from previous runs
    if os.path.isdir(delta_dir):
        shutil.rmtree(delta_dir)
    os.makedirs(delta_dir)

    gen_fsp_upd_delta_blobs(
        cfg_dir=cfg_dir,
        output_dir=delta_dir,
        dlt_files=dlt_paths,
        yaml_file=cfg_input,
        gen_cfg_data_tool=gen_cfg_data_tool)

    delta_blobs = collect_delta_blobs(delta_dir)
    if delta_blobs:
        inject_delta_tags_into_cfgdata(cfg_bin_path, delta_blobs)


def main():
    parser = argparse.ArgumentParser(
        description='Generate FSP UPD per-board delta blobs from YAML defaults')
    parser.add_argument('-c', '--cfg-dir', required=True,
                        help='Directory containing CfgDataDef.yaml and CfgData_Fsp{M,S}.yaml')
    parser.add_argument('-o', '--output-dir', required=True,
                        help='Directory for output delta blobs')
    parser.add_argument('-d', '--dlt', action='append', required=True,
                        help='Per-board DLT file (repeat for each board)')
    parser.add_argument('-y', '--yaml', required=True,
                        help='Path to CfgDataDef.yaml or .pkl file')
    parser.add_argument('-g', '--gencfg', required=True,
                        help='Path to GenCfgData.py tool')
    parser.add_argument('-i', '--inject', default=None,
                        help='Path to CFGDATA.bin; if given, inject delta tags after generation')
    args = parser.parse_args()

    if not os.path.exists(args.output_dir):
        os.makedirs(args.output_dir)

    gen_fsp_upd_delta_blobs(
        cfg_dir=args.cfg_dir,
        output_dir=args.output_dir,
        dlt_files=args.dlt,
        yaml_file=args.yaml,
        gen_cfg_data_tool=args.gencfg,
    )

    if args.inject and os.path.exists(args.inject):
        delta_blobs = collect_delta_blobs(args.output_dir)
        if delta_blobs:
            inject_delta_tags_into_cfgdata(args.inject, delta_blobs)


if __name__ == '__main__':
    main()
