/** @file
  GPIO pins for PTL_PCD PCH.

  Copyright (c) 2026, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

#ifndef _GPIOV2_PINS_PTL_PCD_H_
#define _GPIOV2_PINS_PTL_PCD_H_

#include <Register/GpioV2ChipsetId.h>
#include <Register/GpioAcpiDefines.h>

//
// Unique IDs used in GpioPad defines
//

//
// Community 0
//
#define PTL_PCD_COM_IDX_GPP_V                   0
#define PTL_PCD_GRP_IDX_GPP_V                   0
#define PTL_PCD_COM_IDX_GPP_C                   0
#define PTL_PCD_GRP_IDX_GPP_C                   1

//
// Community 1
//
#define PTL_PCD_COM_IDX_GPP_F                   1
#define PTL_PCD_GRP_IDX_GPP_F                   0
#define PTL_PCD_COM_IDX_GPP_E                   1
#define PTL_PCD_GRP_IDX_GPP_E                   1

//
// Community 3
//
#define PTL_PCD_COM_IDX_CPUJTAG                 2
#define PTL_PCD_GRP_IDX_CPUJTAG                 0
#define PTL_PCD_COM_IDX_GPP_H                   2
#define PTL_PCD_GRP_IDX_GPP_H                   1
#define PTL_PCD_COM_IDX_GPPASPI0                2
#define PTL_PCD_GRP_IDX_GPPASPI0                2
#define PTL_PCD_COM_IDX_VGPIO_3                 2
#define PTL_PCD_GRP_IDX_VGPIO_3                 3

//
// Community 4
//
#define PTL_PCD_COM_IDX_GPP_S                   3
#define PTL_PCD_GRP_IDX_GPP_S                   0

//
// Community 5
//
#define PTL_PCD_COM_IDX_GPP_B                   4
#define PTL_PCD_GRP_IDX_GPP_B                   0
#define PTL_PCD_COM_IDX_GPP_D                   4
#define PTL_PCD_GRP_IDX_GPP_D                   1
#define PTL_PCD_COM_IDX_VGPIO                   4
#define PTL_PCD_GRP_IDX_VGPIO                   2


//
// Group definitions
//
// Com 0
#define PTL_PCD_GROUP_GPP_V                     GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0xFF)
#define PTL_PCD_GROUP_GPP_C                     GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0xFF)
// Com 1
#define PTL_PCD_GROUP_GPP_F                     GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0xFF)
#define PTL_PCD_GROUP_GPP_E                     GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0xFF)
// Com 3
#define PTL_PCD_GROUP_CPUJTAG                   GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_CPUJTAG, PTL_PCD_GRP_IDX_CPUJTAG, 0xFF)
#define PTL_PCD_GROUP_GPP_H                     GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0xFF)
#define PTL_PCD_GROUP_GPPASPI0                  GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0xFF)
#define PTL_PCD_GROUP_VGPIO_3                   GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO_3, PTL_PCD_GRP_IDX_VGPIO_3, 0xFF)
// Com 4
#define PTL_PCD_GROUP_GPP_S                     GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_S, PTL_PCD_GRP_IDX_GPP_S, 0xFF)
// Com 5
#define PTL_PCD_GROUP_GPP_B                     GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0xFF)
#define PTL_PCD_GROUP_GPP_D                     GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0xFF)
#define PTL_PCD_GROUP_VGPIO                     GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0xFF)

//
// GPIO PAD defines
//
// Com 0
#define GPIOV2_PTL_PCD_XXGPP_V_0                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x00)
#define GPIOV2_PTL_PCD_XXGPP_V_1                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x01)
#define GPIOV2_PTL_PCD_XXGPP_V_2                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x02)
#define GPIOV2_PTL_PCD_XXGPP_V_3                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x03)
#define GPIOV2_PTL_PCD_XXGPP_V_4                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x04)
#define GPIOV2_PTL_PCD_XXGPP_V_5                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x05)
#define GPIOV2_PTL_PCD_XXGPP_V_6                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x06)
#define GPIOV2_PTL_PCD_XXGPP_V_7                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x07)
#define GPIOV2_PTL_PCD_XXGPP_V_8                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x08)
#define GPIOV2_PTL_PCD_XXGPP_V_9                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x09)
#define GPIOV2_PTL_PCD_XXGPP_V_10               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x0A)
#define GPIOV2_PTL_PCD_XXGPP_V_11               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x0B)
#define GPIOV2_PTL_PCD_XXGPP_V_12               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x0C)
#define GPIOV2_PTL_PCD_XXGPP_V_13               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x0D)
#define GPIOV2_PTL_PCD_XXGPP_V_14               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x0E)
#define GPIOV2_PTL_PCD_XXGPP_V_15               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x0F)
#define GPIOV2_PTL_PCD_XXGPP_V_16               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x10)
#define GPIOV2_PTL_PCD_XXGPP_V_17               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x11)
#define GPIOV2_PTL_PCD_XXSYS_PWROK              GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x12)
#define GPIOV2_PTL_PCD_XXSYS_RESET_B            GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x13)
#define GPIOV2_PTL_PCD_XXL_BKLTEN               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x14)
#define GPIOV2_PTL_PCD_XXL_BKLTCTL              GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x15)
#define GPIOV2_PTL_PCD_XXL_VDDEN                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x16)
#define GPIOV2_PTL_PCD_XXMLK_RST_B              GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_V, PTL_PCD_GRP_IDX_GPP_V, 0x17)

#define GPIOV2_PTL_PCD_XXGPP_C_0                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x00)
#define GPIOV2_PTL_PCD_XXGPP_C_1                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x01)
#define GPIOV2_PTL_PCD_XXGPP_C_2                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x02)
#define GPIOV2_PTL_PCD_XXGPP_C_3                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x03)
#define GPIOV2_PTL_PCD_XXGPP_C_4                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x04)
#define GPIOV2_PTL_PCD_XXGPP_C_5                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x05)
#define GPIOV2_PTL_PCD_XXGPP_C_6                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x06)
#define GPIOV2_PTL_PCD_XXGPP_C_7                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x07)
#define GPIOV2_PTL_PCD_XXGPP_C_8                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x08)
#define GPIOV2_PTL_PCD_XXGPP_C_9                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x09)
#define GPIOV2_PTL_PCD_XXGPP_C_10               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x0A)
#define GPIOV2_PTL_PCD_XXGPP_C_11               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x0B)
#define GPIOV2_PTL_PCD_XXGPP_C_12               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x0C)
#define GPIOV2_PTL_PCD_XXGPP_C_13               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x0D)
#define GPIOV2_PTL_PCD_XXGPP_C_14               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x0E)
#define GPIOV2_PTL_PCD_XXGPP_C_15               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x0F)
#define GPIOV2_PTL_PCD_XXGPP_C_16               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x10)
#define GPIOV2_PTL_PCD_XXGPP_C_17               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x11)
#define GPIOV2_PTL_PCD_XXGPP_C_18               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x12)
#define GPIOV2_PTL_PCD_XXGPP_C_19               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x13)
#define GPIOV2_PTL_PCD_XXGPP_C_20               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x14)
#define GPIOV2_PTL_PCD_XXGPP_C_21               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x15)
#define GPIOV2_PTL_PCD_XXGPP_C_22               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x16)
#define GPIOV2_PTL_PCD_XXGPP_C_23               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_C, PTL_PCD_GRP_IDX_GPP_C, 0x17)

// Com 1
#define GPIOV2_PTL_PCD_XXGPP_F_0                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x00)
#define GPIOV2_PTL_PCD_XXGPP_F_1                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x01)
#define GPIOV2_PTL_PCD_XXGPP_F_2                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x02)
#define GPIOV2_PTL_PCD_XXGPP_F_3                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x03)
#define GPIOV2_PTL_PCD_XXGPP_F_4                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x04)
#define GPIOV2_PTL_PCD_XXGPP_F_5                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x05)
#define GPIOV2_PTL_PCD_XXGPP_F_6                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x06)
#define GPIOV2_PTL_PCD_XXGPP_F_7                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x07)
#define GPIOV2_PTL_PCD_XXGPP_F_8                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x08)
#define GPIOV2_PTL_PCD_XXGPP_F_9                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x09)
#define GPIOV2_PTL_PCD_XXGPP_F_10               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x0A)
#define GPIOV2_PTL_PCD_XXGPP_F_11               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x0B)
#define GPIOV2_PTL_PCD_XXGPP_F_12               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x0C)
#define GPIOV2_PTL_PCD_XXGPP_F_13               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x0D)
#define GPIOV2_PTL_PCD_XXGPP_F_14               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x0E)
#define GPIOV2_PTL_PCD_XXGPP_F_15               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x0F)
#define GPIOV2_PTL_PCD_XXGPP_F_16               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x10)
#define GPIOV2_PTL_PCD_XXGPP_F_17               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x11)
#define GPIOV2_PTL_PCD_XXGPP_F_18               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x12)
#define GPIOV2_PTL_PCD_XXGPP_F_19               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x13)
#define GPIOV2_PTL_PCD_XXGPP_F_20               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x14)
#define GPIOV2_PTL_PCD_XXGPP_F_21               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x15)
#define GPIOV2_PTL_PCD_XXGPP_F_22               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x16)
#define GPIOV2_PTL_PCD_XXGPP_F_23               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x17)
#define GPIOV2_PTL_PCD_THC1_GSPI1_I3C2_CLK_LOOPBK GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x18)
#define GPIOV2_PTL_PCD_A_GSPI0_CLK_LOOPBK       GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_F, PTL_PCD_GRP_IDX_GPP_F, 0x19)

#define GPIOV2_PTL_PCD_XXGPP_E_0                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x00)
#define GPIOV2_PTL_PCD_XXGPP_E_1                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x01)
#define GPIOV2_PTL_PCD_XXGPP_E_2                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x02)
#define GPIOV2_PTL_PCD_XXGPP_E_3                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x03)
#define GPIOV2_PTL_PCD_XXGPP_E_4                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x04)
#define GPIOV2_PTL_PCD_XXGPP_E_5                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x05)
#define GPIOV2_PTL_PCD_XXGPP_E_6                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x06)
#define GPIOV2_PTL_PCD_XXGPP_E_7                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x07)
#define GPIOV2_PTL_PCD_XXGPP_E_8                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x08)
#define GPIOV2_PTL_PCD_XXGPP_E_9                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x09)
#define GPIOV2_PTL_PCD_XXGPP_E_10               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x0A)
#define GPIOV2_PTL_PCD_XXGPP_E_11               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x0B)
#define GPIOV2_PTL_PCD_XXGPP_E_12               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x0C)
#define GPIOV2_PTL_PCD_XXGPP_E_13               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x0D)
#define GPIOV2_PTL_PCD_XXGPP_E_14               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x0E)
#define GPIOV2_PTL_PCD_XXGPP_E_15               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x0F)
#define GPIOV2_PTL_PCD_XXGPP_E_16               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x10)
#define GPIOV2_PTL_PCD_XXGPP_E_17               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x11)
#define GPIOV2_PTL_PCD_XXGPP_E_18               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x12)
#define GPIOV2_PTL_PCD_XXGPP_E_19               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x13)
#define GPIOV2_PTL_PCD_XXGPP_E_20               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x14)
#define GPIOV2_PTL_PCD_XXGPP_E_21               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x15)
#define GPIOV2_PTL_PCD_XXGPP_E_22               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x16)

#define GPIOV2_PTL_PCD_XXBOOTHALT_B             GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x17)

#define GPIOV2_PTL_PCD_THC0_GSPI0_CLK_LOOPBK    GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_E, PTL_PCD_GRP_IDX_GPP_E, 0x18)

// Com 3
#define GPIOV2_PTL_PCD_XXEPD_ON                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_CPUJTAG, PTL_PCD_GRP_IDX_CPUJTAG, 0x00)
#define GPIOV2_PTL_PCD_XXVDD2_PWRGD             GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_CPUJTAG, PTL_PCD_GRP_IDX_CPUJTAG, 0x01)
#define GPIOV2_PTL_PCD_XXJTAG_MBPB0             GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_CPUJTAG, PTL_PCD_GRP_IDX_CPUJTAG, 0x02)
#define GPIOV2_PTL_PCD_XXJTAG_MBPB1             GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_CPUJTAG, PTL_PCD_GRP_IDX_CPUJTAG, 0x03)
#define GPIOV2_PTL_PCD_XXJTAG_MBPB2             GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_CPUJTAG, PTL_PCD_GRP_IDX_CPUJTAG, 0x04)
#define GPIOV2_PTL_PCD_XXJTAG_MBPB3             GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_CPUJTAG, PTL_PCD_GRP_IDX_CPUJTAG, 0x05)
#define GPIOV2_PTL_PCD_XXJTAG_TDO               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_CPUJTAG, PTL_PCD_GRP_IDX_CPUJTAG, 0x06)
#define GPIOV2_PTL_PCD_XXPRDY_B                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_CPUJTAG, PTL_PCD_GRP_IDX_CPUJTAG, 0x07)
#define GPIOV2_PTL_PCD_XXPREQ_B                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_CPUJTAG, PTL_PCD_GRP_IDX_CPUJTAG, 0x08)
#define GPIOV2_PTL_PCD_XXJTAG_TDI               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_CPUJTAG, PTL_PCD_GRP_IDX_CPUJTAG, 0x09)
#define GPIOV2_PTL_PCD_XXJTAG_TMS               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_CPUJTAG, PTL_PCD_GRP_IDX_CPUJTAG, 0x0A)
#define GPIOV2_PTL_PCD_XXJTAG_TCK               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_CPUJTAG, PTL_PCD_GRP_IDX_CPUJTAG, 0x0B)
#define GPIOV2_PTL_PCD_XXDBG_PMODE              GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_CPUJTAG, PTL_PCD_GRP_IDX_CPUJTAG, 0x0C)
#define GPIOV2_PTL_PCD_XXJTAG_TRST_B            GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_CPUJTAG, PTL_PCD_GRP_IDX_CPUJTAG, 0x0D)
#define GPIOV2_PTL_PCD_XXDDSP_HPDALV            GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_CPUJTAG, PTL_PCD_GRP_IDX_CPUJTAG, 0x0E)

#define GPIOV2_PTL_PCD_XXGPP_H_0                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x00)
#define GPIOV2_PTL_PCD_XXGPP_H_1                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x01)
#define GPIOV2_PTL_PCD_XXGPP_H_2                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x02)
#define GPIOV2_PTL_PCD_XXGPP_H_3                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x03)
#define GPIOV2_PTL_PCD_XXGPP_H_4                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x04)
#define GPIOV2_PTL_PCD_XXGPP_H_5                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x05)
#define GPIOV2_PTL_PCD_XXGPP_H_6                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x06)
#define GPIOV2_PTL_PCD_XXGPP_H_7                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x07)
#define GPIOV2_PTL_PCD_XXGPP_H_8                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x08)
#define GPIOV2_PTL_PCD_XXGPP_H_9                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x09)
#define GPIOV2_PTL_PCD_XXGPP_H_10               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x0A)
#define GPIOV2_PTL_PCD_XXGPP_H_11               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x0B)
#define GPIOV2_PTL_PCD_XXGPP_H_12               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x0C)
#define GPIOV2_PTL_PCD_XXGPP_H_13               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x0D)
#define GPIOV2_PTL_PCD_XXGPP_H_14               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x0E)
#define GPIOV2_PTL_PCD_XXGPP_H_15               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x0F)
#define GPIOV2_PTL_PCD_XXGPP_H_16               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x10)
#define GPIOV2_PTL_PCD_XXGPP_H_17               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x11)
#define GPIOV2_PTL_PCD_XXGPP_H_18               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x12)
#define GPIOV2_PTL_PCD_XXGPP_H_19               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x13)
#define GPIOV2_PTL_PCD_XXGPP_H_20               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x14)
#define GPIOV2_PTL_PCD_XXGPP_H_21               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x15)
#define GPIOV2_PTL_PCD_XXGPP_H_22               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x16)
#define GPIOV2_PTL_PCD_XXGPP_H_23               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x17)
#define GPIOV2_PTL_PCD_XXGPP_H_24               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x18)

#define GPIOV2_PTL_PCD_LPI3C1_CLK_LOOPBK        GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x19)
#define GPIOV2_PTL_PCD_LPI3C0_CLK_LOOPBK        GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x1A)
#define GPIOV2_PTL_PCD_ISHI3C1_CLK_LOOPBK       GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_H, PTL_PCD_GRP_IDX_GPP_H, 0x1B)

#define GPIOV2_PTL_PCD_XXGPP_A_0                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x00)
#define GPIOV2_PTL_PCD_XXGPP_A_1                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x01)
#define GPIOV2_PTL_PCD_XXGPP_A_2                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x02)
#define GPIOV2_PTL_PCD_XXGPP_A_3                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x03)
#define GPIOV2_PTL_PCD_XXGPP_A_4                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x04)
#define GPIOV2_PTL_PCD_XXGPP_A_5                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x05)
#define GPIOV2_PTL_PCD_XXGPP_A_6                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x06)
#define GPIOV2_PTL_PCD_XXGPP_A_7                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x07)
#define GPIOV2_PTL_PCD_XXGPP_A_8                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x08)
#define GPIOV2_PTL_PCD_XXGPP_A_9                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x09)
#define GPIOV2_PTL_PCD_XXGPP_A_10               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x0A)
#define GPIOV2_PTL_PCD_XXGPP_A_11               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x0B)
#define GPIOV2_PTL_PCD_XXGPP_A_12               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x0C)
#define GPIOV2_PTL_PCD_XXGPP_A_13               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x0D)
#define GPIOV2_PTL_PCD_XXGPP_A_14               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x0E)
#define GPIOV2_PTL_PCD_XXGPP_A_15               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x0F)
#define GPIOV2_PTL_PCD_XXGPP_A_16               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x10)
#define GPIOV2_PTL_PCD_XXGPP_A_17               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x11)

#define GPIOV2_PTL_PCD_XXSPI0_IO_2              GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x12)
#define GPIOV2_PTL_PCD_XXSPI0_IO_3              GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x13)
#define GPIOV2_PTL_PCD_XXSPI0_MOSI_IO_0         GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x14)
#define GPIOV2_PTL_PCD_XXSPI0_MISO_IO_1         GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x15)
#define GPIOV2_PTL_PCD_XXSPI0_TPM_CS_B          GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x16)
#define GPIOV2_PTL_PCD_XXSPI0_FLASH_0_CS_B      GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x17)
#define GPIOV2_PTL_PCD_XXSPI0_FLASH_1_CS_B      GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x18)
#define GPIOV2_PTL_PCD_XXSPI0_CLK               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x19)
#define GPIOV2_PTL_PCD_ESPI_CLK_LOOPBK          GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x1A)
#define GPIOV2_PTL_PCD_SPI0_CLK_LOOPBK          GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPPASPI0, PTL_PCD_GRP_IDX_GPPASPI0, 0x1B)

#define GPIOV2_PTL_PCD_VGPIO_USB_0              GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO_3, PTL_PCD_GRP_IDX_VGPIO_3, 0x00)
#define GPIOV2_PTL_PCD_VGPIO_USB_1              GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO_3, PTL_PCD_GRP_IDX_VGPIO_3, 0x01)
#define GPIOV2_PTL_PCD_VGPIO_USB_2              GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO_3, PTL_PCD_GRP_IDX_VGPIO_3, 0x02)
#define GPIOV2_PTL_PCD_VGPIO_USB_3              GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO_3, PTL_PCD_GRP_IDX_VGPIO_3, 0x03)
#define GPIOV2_PTL_PCD_VGPIO_USB_4              GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO_3, PTL_PCD_GRP_IDX_VGPIO_3, 0x04)
#define GPIOV2_PTL_PCD_VGPIO_USB_5              GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO_3, PTL_PCD_GRP_IDX_VGPIO_3, 0x05)
#define GPIOV2_PTL_PCD_VGPIO_USB_6              GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO_3, PTL_PCD_GRP_IDX_VGPIO_3, 0x06)
#define GPIOV2_PTL_PCD_VGPIO_USB_7              GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO_3, PTL_PCD_GRP_IDX_VGPIO_3, 0x07)
#define GPIOV2_PTL_PCD_VGPIO_TS0                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO_3, PTL_PCD_GRP_IDX_VGPIO_3, 0x08)
#define GPIOV2_PTL_PCD_VGPIO_TS1                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO_3, PTL_PCD_GRP_IDX_VGPIO_3, 0x09)
#define GPIOV2_PTL_PCD_VGPIO_THC0               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO_3, PTL_PCD_GRP_IDX_VGPIO_3, 0x0A)
#define GPIOV2_PTL_PCD_VGPIO_THC1               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO_3, PTL_PCD_GRP_IDX_VGPIO_3, 0x0B)
#define GPIOV2_PTL_PCD_VGPIO_THC2               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO_3, PTL_PCD_GRP_IDX_VGPIO_3, 0x0C)
#define GPIOV2_PTL_PCD_VGPIO_THC3               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO_3, PTL_PCD_GRP_IDX_VGPIO_3, 0x0D)

// Com 4
#define GPIOV2_PTL_PCD_XXGPP_S_0                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_S, PTL_PCD_GRP_IDX_GPP_S, 0x00)
#define GPIOV2_PTL_PCD_XXGPP_S_1                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_S, PTL_PCD_GRP_IDX_GPP_S, 0x01)
#define GPIOV2_PTL_PCD_XXGPP_S_2                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_S, PTL_PCD_GRP_IDX_GPP_S, 0x02)
#define GPIOV2_PTL_PCD_XXGPP_S_3                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_S, PTL_PCD_GRP_IDX_GPP_S, 0x03)
#define GPIOV2_PTL_PCD_XXGPP_S_4                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_S, PTL_PCD_GRP_IDX_GPP_S, 0x04)
#define GPIOV2_PTL_PCD_XXGPP_S_5                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_S, PTL_PCD_GRP_IDX_GPP_S, 0x05)
#define GPIOV2_PTL_PCD_XXGPP_S_6                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_S, PTL_PCD_GRP_IDX_GPP_S, 0x06)
#define GPIOV2_PTL_PCD_XXGPP_S_7                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_S, PTL_PCD_GRP_IDX_GPP_S, 0x07)

// Com 5
#define GPIOV2_PTL_PCD_XXGPP_B_0                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x00)
#define GPIOV2_PTL_PCD_XXGPP_B_1                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x01)
#define GPIOV2_PTL_PCD_XXGPP_B_2                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x02)
#define GPIOV2_PTL_PCD_XXGPP_B_3                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x03)
#define GPIOV2_PTL_PCD_XXGPP_B_4                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x04)
#define GPIOV2_PTL_PCD_XXGPP_B_5                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x05)
#define GPIOV2_PTL_PCD_XXGPP_B_6                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x06)
#define GPIOV2_PTL_PCD_XXGPP_B_7                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x07)
#define GPIOV2_PTL_PCD_XXGPP_B_8                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x08)
#define GPIOV2_PTL_PCD_XXGPP_B_9                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x09)
#define GPIOV2_PTL_PCD_XXGPP_B_10               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x0A)
#define GPIOV2_PTL_PCD_XXGPP_B_11               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x0B)
#define GPIOV2_PTL_PCD_XXGPP_B_12               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x0C)
#define GPIOV2_PTL_PCD_XXGPP_B_13               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x0D)
#define GPIOV2_PTL_PCD_XXGPP_B_14               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x0E)
#define GPIOV2_PTL_PCD_XXGPP_B_15               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x0F)
#define GPIOV2_PTL_PCD_XXGPP_B_16               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x10)
#define GPIOV2_PTL_PCD_XXGPP_B_17               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x11)
#define GPIOV2_PTL_PCD_XXGPP_B_18               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x12)
#define GPIOV2_PTL_PCD_XXGPP_B_19               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x13)
#define GPIOV2_PTL_PCD_XXGPP_B_20               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x14)
#define GPIOV2_PTL_PCD_XXGPP_B_21               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x15)
#define GPIOV2_PTL_PCD_XXGPP_B_22               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x16)
#define GPIOV2_PTL_PCD_XXGPP_B_23               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x17)
#define GPIOV2_PTL_PCD_XXGPP_B_24               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x18)
#define GPIOV2_PTL_PCD_XXGPP_B_25               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x19)
#define GPIOV2_PTL_PCD_ISHI3C0_CLK_LOOPBK       GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_B, PTL_PCD_GRP_IDX_GPP_B, 0x1A)

#define GPIOV2_PTL_PCD_XXGPP_D_0                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x00)
#define GPIOV2_PTL_PCD_XXGPP_D_1                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x01)
#define GPIOV2_PTL_PCD_XXGPP_D_2                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x02)
#define GPIOV2_PTL_PCD_XXGPP_D_3                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x03)
#define GPIOV2_PTL_PCD_XXGPP_D_4                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x04)
#define GPIOV2_PTL_PCD_XXGPP_D_5                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x05)
#define GPIOV2_PTL_PCD_XXGPP_D_6                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x06)
#define GPIOV2_PTL_PCD_XXGPP_D_7                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x07)
#define GPIOV2_PTL_PCD_XXGPP_D_8                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x08)
#define GPIOV2_PTL_PCD_XXGPP_D_9                GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x09)
#define GPIOV2_PTL_PCD_XXGPP_D_10               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x0A)
#define GPIOV2_PTL_PCD_XXGPP_D_11               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x0B)
#define GPIOV2_PTL_PCD_XXGPP_D_12               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x0C)
#define GPIOV2_PTL_PCD_XXGPP_D_13               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x0D)
#define GPIOV2_PTL_PCD_XXGPP_D_14               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x0E)
#define GPIOV2_PTL_PCD_XXGPP_D_15               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x0F)
#define GPIOV2_PTL_PCD_XXGPP_D_16               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x10)
#define GPIOV2_PTL_PCD_XXGPP_D_17               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x11)
#define GPIOV2_PTL_PCD_XXGPP_D_18               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x12)
#define GPIOV2_PTL_PCD_XXGPP_D_19               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x13)
#define GPIOV2_PTL_PCD_XXGPP_D_20               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x14)
#define GPIOV2_PTL_PCD_XXGPP_D_21               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x15)
#define GPIOV2_PTL_PCD_XXGPP_D_22               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x16)
#define GPIOV2_PTL_PCD_XXGPP_D_23               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x17)
#define GPIOV2_PTL_PCD_XXGPP_D_24               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x18)
#define GPIOV2_PTL_PCD_XXGPP_D_25               GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x19)
#define GPIOV2_PTL_PCD_SHD_I3C_CLK_LOOPBK       GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_GPP_D, PTL_PCD_GRP_IDX_GPP_D, 0x1A)

#define GPIOV2_PTL_PCD_VGPIO_0                  GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0x00)
#define GPIOV2_PTL_PCD_VGPIO_5                  GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0x01)
#define GPIOV2_PTL_PCD_VGPIO_30                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0x02)
#define GPIOV2_PTL_PCD_VGPIO_31                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0x03)
#define GPIOV2_PTL_PCD_VGPIO_32                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0x04)
#define GPIOV2_PTL_PCD_VGPIO_33                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0x05)
#define GPIOV2_PTL_PCD_VGPIO_34                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0x06)
#define GPIOV2_PTL_PCD_VGPIO_35                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0x07)
#define GPIOV2_PTL_PCD_VGPIO_36                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0x08)
#define GPIOV2_PTL_PCD_VGPIO_37                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0x09)
#define GPIOV2_PTL_PCD_VGPIO_40                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0x0A)
#define GPIOV2_PTL_PCD_VGPIO_41                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0x0B)
#define GPIOV2_PTL_PCD_VGPIO_42                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0x0C)
#define GPIOV2_PTL_PCD_VGPIO_43                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0x0D)
#define GPIOV2_PTL_PCD_VGPIO_44                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0x0E)
#define GPIOV2_PTL_PCD_VGPIO_45                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0x0F)
#define GPIOV2_PTL_PCD_VGPIO_46                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0x10)
#define GPIOV2_PTL_PCD_VGPIO_47                 GPIOV2_PAD_ID (0, GPIOV2_PTL_PCD_CHIPSET_ID, 0, PTL_PCD_COM_IDX_VGPIO, PTL_PCD_GRP_IDX_VGPIO, 0x11)

#endif // _GPIOV2_PINS_PTL_PCD_H_