//
// Automatically generated by GenNvs ver 2.4.7
// Please DO NOT modify !!!
//

/** @file

  Copyright (c) 2026, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent
**/

  //
  // Define Host Bridge NVS Area operation region.
  //
#ifndef _HOST_BRIDGE_NVS_AREA_DEF_H_
#define _HOST_BRIDGE_NVS_AREA_DEF_H_

#pragma pack (push,1)
typedef struct {
  UINT8    LuxLowValue;                             ///< Offset 0       LUX Low Value
  UINT8    LuxHighValue;                            ///< Offset 1       LUX High Value
  UINT32   XPcieCfgBaseAddress;                     ///< Offset 2       Any Device's PCIe Config Space Base Address
  UINT64   Mmio64Base;                              ///< Offset 6       Base of above 4GB MMIO resource
  UINT64   Mmio64Length;                            ///< Offset 14      Length of above 4GB MMIO resource
  UINT32   Mmio32Base;                              ///< Offset 22      Base of below 4GB MMIO resource
  UINT32   Mmio32Length;                            ///< Offset 26      Length of below 4GB MMIO resource
  UINT8    SimicsEnvironment;                       ///< Offset 30      Simics Environment information
} HOST_BRIDGE_NVS_AREA;

#pragma pack(pop)
#endif
