//
// Automatically generated by GenNvs ver 2.4.7
// Please DO NOT modify !!!
//

/**@file

  Copyright (c) 2026, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent
**/

  //
  // Define IPU NVS Area operation region.
  //
#ifndef _IPU_NVS_AREA_DEF_H_
#define _IPU_NVS_AREA_DEF_H_

#pragma pack (push,1)
typedef struct {
  UINT8    IpuAcpiMode;                             ///< Offset 0       IPU ACPI device type (0=Disabled, 1=AVStream virtual device as child of GFX)
} IPU_NVS_AREA;

#pragma pack(pop)
#endif
