//
// Automatically generated by GenNvs ver 2.4.7
// Please DO NOT modify !!!
//

/**@file

  Copyright (c) 2026, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent
**/

  //
  // Define ITBT NVS Area operation region.
  //
#ifndef _I_TBT_NVS_AREA_DEF_H_
#define _I_TBT_NVS_AREA_DEF_H_

#pragma pack (push,1)
typedef struct {
  UINT8    IntegratedTbtSupport;                    ///< Offset 0       Enable/Disable Integrated TbtSupport
  UINT8    IntegratedTbtDma0;                       ///< Offset 1       Integrated DMA0 is supported or not.
  UINT8    IntegratedTbtDma1;                       ///< Offset 2       Integrated DMA1 is supported or not.
  UINT8    ITbtPcieRootPortEn0;                     ///< Offset 3       ITbt Pcie Root Port 0 is enabled or not.
  UINT8    ITbtPcieRootPortEn1;                     ///< Offset 4       ITbt Pcie Root Port 1 is enabled or not.
  UINT8    ITbtPcieRootPortEn2;                     ///< Offset 5       ITbt Pcie Root Port 2 is enabled or not.
  UINT8    ITbtPcieRootPortEn3;                     ///< Offset 6       ITbt Pcie Root Port 3 is enabled or not.
  UINT8    OsNativeResourceBalance;                 ///< Offset 7       OS Native Resource Balance is enable or not.
  UINT8    ITbtRtd3;                                ///< Offset 8       ITBT Rtd3
  UINT16   ITbtRtd3ExitDelay;                       ///< Offset 9       ITBT Rtd3 exit delay, unit is ms
  UINT8    ITbtImrValid;                            ///< Offset 11      ITBT IMR Valid
  UINT16   ITbtForcePowerOnTimeoutInMs;             ///< Offset 12      Timeout value for forcing power iTBT controller on every boot/reboot/Sx exit as a precondition for execution of following mailbox communication.
  UINT16   ITbtConnectTopologyTimeoutInMs;          ///< Offset 14      Timeout value while sending connect topology mailbox command
  UINT8    ITbtVproDockSupport;                     ///< Offset 16      ITBT vPro Dock support
  UINT16   PcieRtd3LinkActiveTimeout;               ///< Offset 17      PCIE RTD3 exit polling Link Active timeout and delay in PS0 before return to OS, unit is ms
} ITBT_NVS_AREA;

#pragma pack(pop)
#endif
