//
// Automatically generated by GenNvs ver 2.4.7
// Please DO NOT modify !!!
//

/**@file

  Copyright (c) 2026, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent
**/

  //
  // Define PCH NVS Area operatino region.
  //
#ifndef _PCH_NVS_AREA_DEF_H_
#define _PCH_NVS_AREA_DEF_H_

#pragma pack (push,1)
typedef struct {
  UINT16   PchSeries;                               ///< Offset 0       PCH Series
  UINT16   PchGeneration;                           ///< Offset 2       PCH Generation
  UINT16   PchStepping;                             ///< Offset 4       PCH Stepping
  UINT32   RpAddress[28];                           ///< Offset 6       Root Port address 1
                                                    ///< Offset 10      Root Port address 2
                                                    ///< Offset 14      Root Port address 3
                                                    ///< Offset 18      Root Port address 4
                                                    ///< Offset 22      Root Port address 5
                                                    ///< Offset 26      Root Port address 6
                                                    ///< Offset 30      Root Port address 7
                                                    ///< Offset 34      Root Port address 8
                                                    ///< Offset 38      Root Port address 9
                                                    ///< Offset 42      Root Port address 10
                                                    ///< Offset 46      Root Port address 11
                                                    ///< Offset 50      Root Port address 12
                                                    ///< Offset 54      Root Port address 13
                                                    ///< Offset 58      Root Port address 14
                                                    ///< Offset 62      Root Port address 15
                                                    ///< Offset 66      Root Port address 16
                                                    ///< Offset 70      Root Port address 17
                                                    ///< Offset 74      Root Port address 18
                                                    ///< Offset 78      Root Port address 19
                                                    ///< Offset 82      Root Port address 20
                                                    ///< Offset 86      Root Port address 21
                                                    ///< Offset 90      Root Port address 22
                                                    ///< Offset 94      Root Port address 23
                                                    ///< Offset 98      Root Port address 24
                                                    ///< Offset 102     Root Port address 25
                                                    ///< Offset 106     Root Port address 26
                                                    ///< Offset 110     Root Port address 27
                                                    ///< Offset 114     Root Port address 28
  UINT64   NHLA[8];                                 ///< Offset 118     HD-Audio NHLT ACPI address 0
                                                    ///< Offset 126     HD-Audio NHLT ACPI address 1
                                                    ///< Offset 134     HD-Audio NHLT ACPI address 2
                                                    ///< Offset 142     HD-Audio NHLT ACPI address 3
                                                    ///< Offset 150     HD-Audio NHLT ACPI address 4
                                                    ///< Offset 158     HD-Audio NHLT ACPI address 5
                                                    ///< Offset 166     HD-Audio NHLT ACPI address 6
                                                    ///< Offset 174     HD-Audio NHLT ACPI address 7
  UINT32   NHLL[8];                                 ///< Offset 182     HD-Audio NHLT ACPI length  0
                                                    ///< Offset 186     HD-Audio NHLT ACPI length  1
                                                    ///< Offset 190     HD-Audio NHLT ACPI length  2
                                                    ///< Offset 194     HD-Audio NHLT ACPI length  3
                                                    ///< Offset 198     HD-Audio NHLT ACPI length  4
                                                    ///< Offset 202     HD-Audio NHLT ACPI length  5
                                                    ///< Offset 206     HD-Audio NHLT ACPI length  6
                                                    ///< Offset 210     HD-Audio NHLT ACPI length  7
  UINT32   ADFM;                                    ///< Offset 214     HD-Audio DSP Feature Mask
  UINT8    SWQ0;                                    ///< Offset 218     HD-Audio SoundWire Link #1 quirk mask
  UINT8    SWQ1;                                    ///< Offset 219     HD-Audio SoundWire Link #2 quirk mask
  UINT8    SWQ2;                                    ///< Offset 220     HD-Audio SoundWire Link #3 quirk mask
  UINT8    SWQ3;                                    ///< Offset 221     HD-Audio SoundWire Link #4 quirk mask
  UINT8    SWQ4;                                    ///< Offset 222     HD-Audio SoundWire Link #5 quirk mask
  UINT8    ACS0;                                    ///< Offset 223     HD-Audio SoundWire Link #1 Autonomous Clock Stop
  UINT8    ACS1;                                    ///< Offset 224     HD-Audio SoundWire Link #2 Autonomous Clock Stop
  UINT8    ACS2;                                    ///< Offset 225     HD-Audio SoundWire Link #3 Autonomous Clock Stop
  UINT8    ACS3;                                    ///< Offset 226     HD-Audio SoundWire Link #4 Autonomous Clock Stop
  UINT8    ACS4;                                    ///< Offset 227     HD-Audio SoundWire Link #5 Autonomous Clock Stop
  UINT8    DAI0;                                    ///< Offset 228     HD-Audio SoundWire Link #1 Data On Active Interval Select
  UINT8    DAI1;                                    ///< Offset 229     HD-Audio SoundWire Link #2 Data On Active Interval Select
  UINT8    DAI2;                                    ///< Offset 230     HD-Audio SoundWire Link #3 Data On Active Interval Select
  UINT8    DAI3;                                    ///< Offset 231     HD-Audio SoundWire Link #4 Data On Active Interval Select
  UINT8    DAI4;                                    ///< Offset 232     HD-Audio SoundWire Link #5 Data On Active Interval Select
  UINT8    DAE0;                                    ///< Offset 233     HD-Audio SoundWire Link #1 Data On Active Interval Extension Select
  UINT8    DAE1;                                    ///< Offset 234     HD-Audio SoundWire Link #2 Data On Active Interval Extension Select
  UINT8    DAE2;                                    ///< Offset 235     HD-Audio SoundWire Link #3 Data On Active Interval Extension Select
  UINT8    DAE3;                                    ///< Offset 236     HD-Audio SoundWire Link #4 Data On Active Interval Extension Select
  UINT8    DAE4;                                    ///< Offset 237     HD-Audio SoundWire Link #5 Data On Active Interval Extension Select
  UINT8    DAX0;                                    ///< Offset 238     HD-Audio SoundWire Link #1 Data On Active Interval Extension 2 Select
  UINT8    DAX1;                                    ///< Offset 239     HD-Audio SoundWire Link #2 Data On Active Interval Extension 2 Select
  UINT8    DAX2;                                    ///< Offset 240     HD-Audio SoundWire Link #3 Data On Active Interval Extension 2 Select
  UINT8    DAX3;                                    ///< Offset 241     HD-Audio SoundWire Link #4 Data On Active Interval Extension 2 Select
  UINT8    DAX4;                                    ///< Offset 242     HD-Audio SoundWire Link #5 Data On Active Interval Extension 2 Select
  UINT8    DOD0;                                    ///< Offset 243     HD-Audio SoundWire Link #1 Data On Delay Select
  UINT8    DOD1;                                    ///< Offset 244     HD-Audio SoundWire Link #2 Data On Delay Select
  UINT8    DOD2;                                    ///< Offset 245     HD-Audio SoundWire Link #3 Data On Delay Select
  UINT8    DOD3;                                    ///< Offset 246     HD-Audio SoundWire Link #4 Data On Delay Select
  UINT8    DOD4;                                    ///< Offset 247     HD-Audio SoundWire Link #5 Data On Delay Select
  UINT8    DOE0;                                    ///< Offset 248     HD-Audio SoundWire Link #1 Data On Delay Extension Select
  UINT8    DOE1;                                    ///< Offset 249     HD-Audio SoundWire Link #2 Data On Delay Extension Select
  UINT8    DOE2;                                    ///< Offset 250     HD-Audio SoundWire Link #3 Data On Delay Extension Select
  UINT8    DOE3;                                    ///< Offset 251     HD-Audio SoundWire Link #4 Data On Delay Extension Select
  UINT8    DOE4;                                    ///< Offset 252     HD-Audio SoundWire Link #5 Data On Delay Extension Select
  UINT8    DOX0;                                    ///< Offset 253     HD-Audio SoundWire Link #1 Data On Delay Extension 2 Select
  UINT8    DOX1;                                    ///< Offset 254     HD-Audio SoundWire Link #2 Data On Delay Extension 2 Select
  UINT8    DOX2;                                    ///< Offset 255     HD-Audio SoundWire Link #3 Data On Delay Extension 2 Select
  UINT8    DOX3;                                    ///< Offset 256     HD-Audio SoundWire Link #4 Data On Delay Extension 2 Select
  UINT8    DOX4;                                    ///< Offset 257     HD-Audio SoundWire Link #5 Data On Delay Extension 2 Select
  UINT8    CLE0;                                    ///< Offset 258     HD-Audio SoundWire Link #1 Clock Loopback Delay Enable
  UINT8    CLE1;                                    ///< Offset 259     HD-Audio SoundWire Link #2 Clock Loopback Delay Enable
  UINT8    CLE2;                                    ///< Offset 260     HD-Audio SoundWire Link #3 Clock Loopback Delay Enable
  UINT8    CLE3;                                    ///< Offset 261     HD-Audio SoundWire Link #4 Clock Loopback Delay Enable
  UINT8    CLE4;                                    ///< Offset 262     HD-Audio SoundWire Link #5 Clock Loopback Delay Enable
  UINT8    CLT0;                                    ///< Offset 263     HD-Audio SoundWire Link #1 Clock Loopback Delay Time Select
  UINT8    CLT1;                                    ///< Offset 264     HD-Audio SoundWire Link #2 Clock Loopback Delay Time Select
  UINT8    CLT2;                                    ///< Offset 265     HD-Audio SoundWire Link #3 Clock Loopback Delay Time Select
  UINT8    CLT3;                                    ///< Offset 266     HD-Audio SoundWire Link #4 Clock Loopback Delay Time Select
  UINT8    CLT4;                                    ///< Offset 267     HD-Audio SoundWire Link #5 Clock Loopback Delay Time Select
  UINT8    CLS0;                                    ///< Offset 268     HD-Audio SoundWire Link #1 Clock Loopback Source Select
  UINT8    CLS1;                                    ///< Offset 269     HD-Audio SoundWire Link #2 Clock Loopback Source Select
  UINT8    CLS2;                                    ///< Offset 270     HD-Audio SoundWire Link #3 Clock Loopback Source Select
  UINT8    CLS3;                                    ///< Offset 271     HD-Audio SoundWire Link #4 Clock Loopback Source Select
  UINT8    CLS4;                                    ///< Offset 272     HD-Audio SoundWire Link #5 Clock Loopback Source Select
  UINT16   HDBO;                                    ///< Offset 273     HD-Audio Discrete BT Offload
  UINT8    SWMC;                                    ///< Offset 275     HD-Audio SoundWire Host Count
  UINT32   XTAL;                                    ///< Offset 276     XTAL frequency: 0: 24MHz; 1: 38.4MHz; 2: Unsupported
  UINT64   SBRG;                                    ///< Offset 280     SBREG_BAR
  UINT8    GEI0;                                    ///< Offset 288     GPIO GroupIndex mapped to GPE_DW0
  UINT8    GEI1;                                    ///< Offset 289     GPIO GroupIndex mapped to GPE_DW1
  UINT8    GEI2;                                    ///< Offset 290     GPIO GroupIndex mapped to GPE_DW2
  UINT8    GED0;                                    ///< Offset 291     GPIO DW part of group mapped to GPE_DW0
  UINT8    GED1;                                    ///< Offset 292     GPIO DW part of group mapped to GPE_DW1
  UINT8    GED2;                                    ///< Offset 293     GPIO DW part of group mapped to GPE_DW2
  UINT16   PcieLtrMaxSnoopLatency[28];              ///< Offset 294     PCIE LTR max snoop Latency 1
                                                    ///< Offset 296     PCIE LTR max snoop Latency 2
                                                    ///< Offset 298     PCIE LTR max snoop Latency 3
                                                    ///< Offset 300     PCIE LTR max snoop Latency 4
                                                    ///< Offset 302     PCIE LTR max snoop Latency 5
                                                    ///< Offset 304     PCIE LTR max snoop Latency 6
                                                    ///< Offset 306     PCIE LTR max snoop Latency 7
                                                    ///< Offset 308     PCIE LTR max snoop Latency 8
                                                    ///< Offset 310     PCIE LTR max snoop Latency 9
                                                    ///< Offset 312     PCIE LTR max snoop Latency 10
                                                    ///< Offset 314     PCIE LTR max snoop Latency 11
                                                    ///< Offset 316     PCIE LTR max snoop Latency 12
                                                    ///< Offset 318     PCIE LTR max snoop Latency 13
                                                    ///< Offset 320     PCIE LTR max snoop Latency 14
                                                    ///< Offset 322     PCIE LTR max snoop Latency 15
                                                    ///< Offset 324     PCIE LTR max snoop Latency 16
                                                    ///< Offset 326     PCIE LTR max snoop Latency 17
                                                    ///< Offset 328     PCIE LTR max snoop Latency 18
                                                    ///< Offset 330     PCIE LTR max snoop Latency 19
                                                    ///< Offset 332     PCIE LTR max snoop Latency 20
                                                    ///< Offset 334     PCIE LTR max snoop Latency 21
                                                    ///< Offset 336     PCIE LTR max snoop Latency 22
                                                    ///< Offset 338     PCIE LTR max snoop Latency 23
                                                    ///< Offset 340     PCIE LTR max snoop Latency 24
                                                    ///< Offset 342     PCIE LTR max snoop Latency 25
                                                    ///< Offset 344     PCIE LTR max snoop Latency 26
                                                    ///< Offset 346     PCIE LTR max snoop Latency 27
                                                    ///< Offset 348     PCIE LTR max snoop Latency 28
  UINT16   PcieLtrMaxNoSnoopLatency[28];            ///< Offset 350     PCIE LTR max no snoop Latency 1
                                                    ///< Offset 352     PCIE LTR max no snoop Latency 2
                                                    ///< Offset 354     PCIE LTR max no snoop Latency 3
                                                    ///< Offset 356     PCIE LTR max no snoop Latency 4
                                                    ///< Offset 358     PCIE LTR max no snoop Latency 5
                                                    ///< Offset 360     PCIE LTR max no snoop Latency 6
                                                    ///< Offset 362     PCIE LTR max no snoop Latency 7
                                                    ///< Offset 364     PCIE LTR max no snoop Latency 8
                                                    ///< Offset 366     PCIE LTR max no snoop Latency 9
                                                    ///< Offset 368     PCIE LTR max no snoop Latency 10
                                                    ///< Offset 370     PCIE LTR max no snoop Latency 11
                                                    ///< Offset 372     PCIE LTR max no snoop Latency 12
                                                    ///< Offset 374     PCIE LTR max no snoop Latency 13
                                                    ///< Offset 376     PCIE LTR max no snoop Latency 14
                                                    ///< Offset 378     PCIE LTR max no snoop Latency 15
                                                    ///< Offset 380     PCIE LTR max no snoop Latency 16
                                                    ///< Offset 382     PCIE LTR max no snoop Latency 17
                                                    ///< Offset 384     PCIE LTR max no snoop Latency 18
                                                    ///< Offset 386     PCIE LTR max no snoop Latency 19
                                                    ///< Offset 388     PCIE LTR max no snoop Latency 20
                                                    ///< Offset 390     PCIE LTR max no snoop Latency 21
                                                    ///< Offset 392     PCIE LTR max no snoop Latency 22
                                                    ///< Offset 394     PCIE LTR max no snoop Latency 23
                                                    ///< Offset 396     PCIE LTR max no snoop Latency 24
                                                    ///< Offset 398     PCIE LTR max no snoop Latency 25
                                                    ///< Offset 400     PCIE LTR max no snoop Latency 26
                                                    ///< Offset 402     PCIE LTR max no snoop Latency 27
                                                    ///< Offset 404     PCIE LTR max no snoop Latency 28
  UINT32   HPTB;                                    ///< Offset 406     HPET base address
  UINT8    HPTE;                                    ///< Offset 410     HPET enable
  //SerialIo block
  UINT8    SM0[7];                                  ///< Offset 411     SerialIo SPI Controller 0 Mode
                                                    ///< Offset 412     SerialIo SPI Controller 1 Mode
                                                    ///< Offset 413     SerialIo SPI Controller 2 Mode
                                                    ///< Offset 414     SerialIo SPI Controller 3 Mode
                                                    ///< Offset 415     SerialIo SPI Controller 4 Mode
                                                    ///< Offset 416     SerialIo SPI Controller 5 Mode
                                                    ///< Offset 417     SerialIo SPI Controller 6 Mode
  UINT64   SC0[7];                                  ///< Offset 418     SerialIo SPI Controller 0 Pci Config
                                                    ///< Offset 426     SerialIo SPI Controller 1 Pci Config
                                                    ///< Offset 434     SerialIo SPI Controller 2 Pci Config
                                                    ///< Offset 442     SerialIo SPI Controller 3 Pci Config
                                                    ///< Offset 450     SerialIo SPI Controller 4 Pci Config
                                                    ///< Offset 458     SerialIo SPI Controller 5 Pci Config
                                                    ///< Offset 466     SerialIo SPI Controller 6 Pci Config
  UINT8    IM0[8];                                  ///< Offset 474     SerialIo I2C Controller 0 Mode
                                                    ///< Offset 475     SerialIo I2C Controller 1 Mode
                                                    ///< Offset 476     SerialIo I2C Controller 2 Mode
                                                    ///< Offset 477     SerialIo I2C Controller 3 Mode
                                                    ///< Offset 478     SerialIo I2C Controller 4 Mode
                                                    ///< Offset 479     SerialIo I2C Controller 5 Mode
                                                    ///< Offset 480     SerialIo I2C Controller 6 Mode
                                                    ///< Offset 481     SerialIo I2C Controller 7 Mode
  UINT64   IC0[8];                                  ///< Offset 482     SerialIo I2C Controller 0 Pci Config
                                                    ///< Offset 490     SerialIo I2C Controller 1 Pci Config
                                                    ///< Offset 498     SerialIo I2C Controller 2 Pci Config
                                                    ///< Offset 506     SerialIo I2C Controller 3 Pci Config
                                                    ///< Offset 514     SerialIo I2C Controller 4 Pci Config
                                                    ///< Offset 522     SerialIo I2C Controller 5 Pci Config
                                                    ///< Offset 530     SerialIo I2C Controller 6 Pci Config
                                                    ///< Offset 538     SerialIo I2C Controller 7 Pci Config
  UINT8    UM0[7];                                  ///< Offset 546     SerialIo UART Controller 0 Mode
                                                    ///< Offset 547     SerialIo UART Controller 1 Mode
                                                    ///< Offset 548     SerialIo UART Controller 2 Mode
                                                    ///< Offset 549     SerialIo UART Controller 3 Mode
                                                    ///< Offset 550     SerialIo UART Controller 4 Mode
                                                    ///< Offset 551     SerialIo UART Controller 5 Mode
                                                    ///< Offset 552     SerialIo UART Controller 6 Mode
  UINT64   UC0[7];                                  ///< Offset 553     SerialIo UART Controller 0 Pci Config
                                                    ///< Offset 561     SerialIo UART Controller 1 Pci Config
                                                    ///< Offset 569     SerialIo UART Controller 2 Pci Config
                                                    ///< Offset 577     SerialIo UART Controller 3 Pci Config
                                                    ///< Offset 585     SerialIo UART Controller 4 Pci Config
                                                    ///< Offset 593     SerialIo UART Controller 5 Pci Config
                                                    ///< Offset 601     SerialIo UART Controller 6 Pci Config
  UINT8    UD0[7];                                  ///< Offset 609     SerialIo UART Controller 0 DmaEnable
                                                    ///< Offset 610     SerialIo UART Controller 1 DmaEnable
                                                    ///< Offset 611     SerialIo UART Controller 2 DmaEnable
                                                    ///< Offset 612     SerialIo UART Controller 3 DmaEnable
                                                    ///< Offset 613     SerialIo UART Controller 4 DmaEnable
                                                    ///< Offset 614     SerialIo UART Controller 5 DmaEnable
                                                    ///< Offset 615     SerialIo UART Controller 6 DmaEnable
  UINT8    UP0[7];                                  ///< Offset 616     SerialIo UART Controller 0 Power Gating
                                                    ///< Offset 617     SerialIo UART Controller 1 Power Gating
                                                    ///< Offset 618     SerialIo UART Controller 2 Power Gating
                                                    ///< Offset 619     SerialIo UART Controller 3 Power Gating
                                                    ///< Offset 620     SerialIo UART Controller 4 Power Gating
                                                    ///< Offset 621     SerialIo UART Controller 5 Power Gating
                                                    ///< Offset 622     SerialIo UART Controller 6 Power Gating
  UINT8    UI0[7];                                  ///< Offset 623     SerialIo UART Controller 0 Irq
                                                    ///< Offset 624     SerialIo UART Controller 1 Irq
                                                    ///< Offset 625     SerialIo UART Controller 2 Irq
                                                    ///< Offset 626     SerialIo UART Controller 3 Irq
                                                    ///< Offset 627     SerialIo UART Controller 4 Irq
                                                    ///< Offset 628     SerialIo UART Controller 5 Irq
                                                    ///< Offset 629     SerialIo UART Controller 6 Irq
  //end of SerialIo block
  UINT8    SGIR;                                    ///< Offset 630     GPIO IRQ
  UINT8    GPHD;                                    ///< Offset 631     Hide GPIO ACPI device
  UINT8    RstPcieStorageInterfaceType[3];          ///< Offset 632     RST PCIe Storage Cycle Router#1 Interface Type
                                                    ///< Offset 633     RST PCIe Storage Cycle Router#2 Interface Type
                                                    ///< Offset 634     RST PCIe Storage Cycle Router#3 Interface Type
  UINT8    RstPcieStoragePmCapPtr[3];               ///< Offset 635     RST PCIe Storage Cycle Router#1 Power Management Capability Pointer
                                                    ///< Offset 636     RST PCIe Storage Cycle Router#2 Power Management Capability Pointer
                                                    ///< Offset 637     RST PCIe Storage Cycle Router#3 Power Management Capability Pointer
  UINT8    RstPcieStoragePcieCapPtr[3];             ///< Offset 638     RST PCIe Storage Cycle Router#1 PCIe Capabilities Pointer
                                                    ///< Offset 639     RST PCIe Storage Cycle Router#2 PCIe Capabilities Pointer
                                                    ///< Offset 640     RST PCIe Storage Cycle Router#3 PCIe Capabilities Pointer
  UINT16   RstPcieStorageL1ssCapPtr[3];             ///< Offset 641     RST PCIe Storage Cycle Router#1 L1SS Capability Pointer
                                                    ///< Offset 643     RST PCIe Storage Cycle Router#2 L1SS Capability Pointer
                                                    ///< Offset 645     RST PCIe Storage Cycle Router#3 L1SS Capability Pointer
  UINT8    RstPcieStorageEpL1ssControl2[3];         ///< Offset 647     RST PCIe Storage Cycle Router#1 Endpoint L1SS Control Data2
                                                    ///< Offset 648     RST PCIe Storage Cycle Router#2 Endpoint L1SS Control Data2
                                                    ///< Offset 649     RST PCIe Storage Cycle Router#3 Endpoint L1SS Control Data2
  UINT32   RstPcieStorageEpL1ssControl1[3];         ///< Offset 650     RST PCIe Storage Cycle Router#1 Endpoint L1SS Control Data1
                                                    ///< Offset 654     RST PCIe Storage Cycle Router#2 Endpoint L1SS Control Data1
                                                    ///< Offset 658     RST PCIe Storage Cycle Router#3 Endpoint L1SS Control Data1
  UINT16   RstPcieStorageLtrCapPtr[3];              ///< Offset 662     RST PCIe Storage Cycle Router#1 LTR Capability Pointer
                                                    ///< Offset 664     RST PCIe Storage Cycle Router#2 LTR Capability Pointer
                                                    ///< Offset 666     RST PCIe Storage Cycle Router#3 LTR Capability Pointer
  UINT32   RstPcieStorageEpLtrData[3];              ///< Offset 668     RST PCIe Storage Cycle Router#1 Endpoint LTR Data
                                                    ///< Offset 672     RST PCIe Storage Cycle Router#2 Endpoint LTR Data
                                                    ///< Offset 676     RST PCIe Storage Cycle Router#3 Endpoint LTR Data
  UINT16   RstPcieStorageEpLctlData16[3];           ///< Offset 680     RST PCIe Storage Cycle Router#1 Endpoint LCTL Data
                                                    ///< Offset 682     RST PCIe Storage Cycle Router#2 Endpoint LCTL Data
                                                    ///< Offset 684     RST PCIe Storage Cycle Router#3 Endpoint LCTL Data
  UINT16   RstPcieStorageEpDctlData16[3];           ///< Offset 686     RST PCIe Storage Cycle Router#1 Endpoint DCTL Data
                                                    ///< Offset 688     RST PCIe Storage Cycle Router#2 Endpoint DCTL Data
                                                    ///< Offset 690     RST PCIe Storage Cycle Router#3 Endpoint DCTL Data
  UINT16   RstPcieStorageEpDctl2Data16[3];          ///< Offset 692     RST PCIe Storage Cycle Router#1 Endpoint DCTL2 Data
                                                    ///< Offset 694     RST PCIe Storage Cycle Router#2 Endpoint DCTL2 Data
                                                    ///< Offset 696     RST PCIe Storage Cycle Router#3 Endpoint DCTL2 Data
  UINT16   RstPcieStorageRpDctl2Data16[3];          ///< Offset 698     RST PCIe Storage Cycle Router#1 RootPort DCTL2 Data
                                                    ///< Offset 700     RST PCIe Storage Cycle Router#2 RootPort DCTL2 Data
                                                    ///< Offset 702     RST PCIe Storage Cycle Router#3 RootPort DCTL2 Data
  UINT32   RstPcieStorageUniqueTableBar[3];         ///< Offset 704     RST PCIe Storage Cycle Router#1 Endpoint unique MSI-X Table BAR
                                                    ///< Offset 708     RST PCIe Storage Cycle Router#2 Endpoint unique MSI-X Table BAR
                                                    ///< Offset 712     RST PCIe Storage Cycle Router#3 Endpoint unique MSI-X Table BAR
  UINT32   RstPcieStorageUniqueTableBarValue[3];    ///< Offset 716     RST PCIe Storage Cycle Router#1 Endpoint unique MSI-X Table BAR value
                                                    ///< Offset 720     RST PCIe Storage Cycle Router#2 Endpoint unique MSI-X Table BAR value
                                                    ///< Offset 724     RST PCIe Storage Cycle Router#3 Endpoint unique MSI-X Table BAR value
  UINT32   RstPcieStorageUniquePbaBar[3];           ///< Offset 728     RST PCIe Storage Cycle Router#1 Endpoint unique MSI-X PBA BAR
                                                    ///< Offset 732     RST PCIe Storage Cycle Router#2 Endpoint unique MSI-X PBA BAR
                                                    ///< Offset 736     RST PCIe Storage Cycle Router#3 Endpoint unique MSI-X PBA BAR
  UINT32   RstPcieStorageUniquePbaBarValue[3];      ///< Offset 740     RST PCIe Storage Cycle Router#1 Endpoint unique MSI-X PBA BAR value
                                                    ///< Offset 744     RST PCIe Storage Cycle Router#2 Endpoint unique MSI-X PBA BAR value
                                                    ///< Offset 748     RST PCIe Storage Cycle Router#3 Endpoint unique MSI-X PBA BAR value
  UINT32   RstPcieStorageRootPortNum[3];            ///< Offset 752     RST PCIe Storage Cycle Router#1 Root Port number
                                                    ///< Offset 756     RST PCIe Storage Cycle Router#2 Root Port number
                                                    ///< Offset 760     RST PCIe Storage Cycle Router#3 Root Port number
  UINT8    EMH4;                                    ///< Offset 764     eMMC HS400 mode enabled
  UINT8    EMDS;                                    ///< Offset 765     eMMC Driver Strength
  UINT8    CpuSku;                                  ///< Offset 766     CPU SKU
  UINT16   IoTrapAddress[4];                        ///< Offset 767
  UINT8    IoTrapStatus[4];                         ///< Offset 775
  UINT16   PMBS;                                    ///< Offset 779     ACPI IO BASE address
  UINT64   PWRM;                                    ///< Offset 781     PWRM MEM BASE address
  // CNVi specific
  UINT8    CnviCrfPresent;                          ///< Offset 789     CNVi CRF Present
  UINT16   CnviPortId;                              ///< Offset 790     CNVi Sideband Port ID
  UINT8    CnviWifiCore;                            ///< Offset 792     CNVi WiFi Core
  UINT8    CnviBtCore;                              ///< Offset 793     CNVi BT Core
  UINT8    CnviBtInterface;                         ///< Offset 794     CNVi BT Interface
  UINT8    CnviBtAudioOffload;                      ///< Offset 795     CNVi BT Audio Offload
  UINT8    CnviBtAudioOffloadInterface;             ///< Offset 796     CNVi BT Audio Offload Interface
  UINT8    CnviVPro;                                ///< Offset 797     CNVi vPro
  UINT8    CnviDdrRfim;                             ///< Offset 798     CNVi DDR RFI Mitigation
  // TraceHub
  UINT8    TraceVerbosity;                          ///< Offset 799     BIOS trace verbosity
  UINT32   TraceHubFwBase;                          ///< Offset 800     BIOS Trace Hub FW base address
  // PCH PS_ON support
  UINT8    PsOnEnable;                              ///< Offset 804     PCH PS_ON enable
  //
  // These are for PchApciTablesSelfTest use
  //
  UINT8    LtrEnable[28];                           ///< Offset 805     Latency Tolerance Reporting Enable
                                                    ///< Offset 806     Latency Tolerance Reporting Enable
                                                    ///< Offset 807     Latency Tolerance Reporting Enable
                                                    ///< Offset 808     Latency Tolerance Reporting Enable
                                                    ///< Offset 809     Latency Tolerance Reporting Enable
                                                    ///< Offset 810     Latency Tolerance Reporting Enable
                                                    ///< Offset 811     Latency Tolerance Reporting Enable
                                                    ///< Offset 812     Latency Tolerance Reporting Enable
                                                    ///< Offset 813     Latency Tolerance Reporting Enable
                                                    ///< Offset 814     Latency Tolerance Reporting Enable
                                                    ///< Offset 815     Latency Tolerance Reporting Enable
                                                    ///< Offset 816     Latency Tolerance Reporting Enable
                                                    ///< Offset 817     Latency Tolerance Reporting Enable
                                                    ///< Offset 818     Latency Tolerance Reporting Enable
                                                    ///< Offset 819     Latency Tolerance Reporting Enable
                                                    ///< Offset 820     Latency Tolerance Reporting Enable
                                                    ///< Offset 821     Latency Tolerance Reporting Enable
                                                    ///< Offset 822     Latency Tolerance Reporting Enable
                                                    ///< Offset 823     Latency Tolerance Reporting Enable
                                                    ///< Offset 824     Latency Tolerance Reporting Enable
                                                    ///< Offset 825     Latency Tolerance Reporting Enable
                                                    ///< Offset 826     Latency Tolerance Reporting Enable
                                                    ///< Offset 827     Latency Tolerance Reporting Enable
                                                    ///< Offset 828     Latency Tolerance Reporting Enable
                                                    ///< Offset 829     Latency Tolerance Reporting Enable
                                                    ///< Offset 830     Latency Tolerance Reporting Enable
                                                    ///< Offset 831     Latency Tolerance Reporting Enable
                                                    ///< Offset 832     Latency Tolerance Reporting Enable
  UINT8    GBES;                                    ///< Offset 833     GbE Support
  UINT32   PchxDCIPwrDnScale;                       ///< Offset 834     PCH xDCI Power Down Scale Value, DWC_USB3_GCTL_INIT[31:19]
  UINT8    EmmcEnabled;                             ///< Offset 838     Set to indicate that eMMC is enabled
  UINT8    SdCardEnabled;                           ///< Offset 839     Set to indicate that SD card is enabled
  UINT8    EnableTimedGpio0;                        ///< Offset 840     Set to indicate that Timed GPIO 0 is enabled
  UINT8    EnableTimedGpio1;                        ///< Offset 841     Set to indicate that Timed GPIO 1 is enabled
  UINT8    ClockToRootPortMap[18];                  ///< Offset 842     CLOCK index to root port index map. Used during PCIe D3Cold flows
  UINT16   TcoBase;                                 ///< Offset 860     TCO base address
  UINT16   IclkPid;                                 ///< Offset 862     Iclk PID number
  UINT8    PchUsb2PortCount;                        ///< Offset 864     Number of USB2 ports in PCH
  UINT8    PchUsb3PortCount;                        ///< Offset 865     Number of USB3 ports in PCH
  UINT8    SataPortPresence;                        ///< Offset 866     Holds information from SATA PCS register about SATA ports which recieved COMINIT from connected devices.
  UINT8    ClkreqIpcCmdSupported;                   ///< Offset 867     PCIE CLKREQ IPC command support
  UINT32   ThcWakOnTouchInterrupt[2];               ///< Offset 868     Touch Host Controller Wake On Touch Interrupt Number - when 0 wake is disabled
  UINT16   ThcMode[2];                              ///< Offset 876     Touch Host Controller Mode THC or HID over SPI
  UINT8    Ufs0Enabled;                             ///< Offset 880     Is UFS0 Enabled
  UINT8    Ufs1Enabled;                             ///< Offset 881     Is UFS1 Enabled
  UINT8    UaolEnabled;                             ///< Offset 882     Is USB Audio Offload enabled
  UINT32   ThcResetPad[2];                          ///< Offset 883     Touch Host Controller Reset Pad
  UINT8    ThcResetPadTrigger[2];                   ///< Offset 891     Touch Host Controller Reset Pad Trigger
  UINT32   ThcHidSpiConnectionSpeed[2];             ///< Offset 893     Touch Host Controller HID over SPI Connection Speed
  UINT32   ThcHidSpiInputReportHeaderAddress[2];    ///< Offset 901     Touch Host Controller HID over SPI Input Report Header Address
  UINT32   ThcHidSpiInputReportBodyAddress[2];      ///< Offset 909     Touch Host Controller HID over SPI Input Report Body Address
  UINT32   ThcHidSpiOutputReportAddress[2];         ///< Offset 917     Touch Host Controller HID over SPI Output Report Address
  UINT32   ThcHidSpiReadOpcode[2];                  ///< Offset 925     Touch Host Controller HID over SPI Read Opcode
  UINT32   ThcHidSpiWriteOpcode[2];                 ///< Offset 933     Touch Host Controller HID over SPI Write Opcode
  UINT32   ThcHidSpiFlags[2];                       ///< Offset 941     Touch Host Controller HID over SPI Flags
  UINT32   ThcActiveLtr[2];                         ///< Offset 949     Touch Host Controller Active Ltr
  UINT32   ThcIdleLtr[2];                           ///< Offset 957     Touch Host Controller Idle Ltr
  UINT32   ThcHidSpiLimitPacketSize[2];             ///< Offset 965     Touch Host Controller Limit Packet Size
  UINT32   ThcPerformanceLimitation[2];             ///< Offset 973     Touch Host Controller Performance Limitation
  UINT32   ThcDisplayFrameSyncPeriod[2];            ///< Offset 981     Touch Host Controller Display Frame Sync Period
  UINT32   ThcResetSequencingDelay[2];              ///< Offset 989     Touch Host Controller Reset Sequencing Delay
  UINT16   ThcHidI2cDeviceAddress[2];               ///< Offset 997     Touch Host Controller HID over I2C Descriptor Address
  UINT32   ThcHidI2cConnectionSpeed[2];             ///< Offset 1001    Touch Host Controller HID over I2C Connection Speed
  UINT8    ThcHidI2cAddressingMode[2];              ///< Offset 1009    Touch Host Controller HID over I2C Addressing Mode
  UINT64   ThcHidI2cStandardModeSerialClockLineHighPeriod[2]; ///< Offset 1011    Touch Host Controller HID over I2C Serial Clock Line High Period
  UINT64   ThcHidI2cStandardModeSerialClockLineLowPeriod[2]; ///< Offset 1027    Touch Host Controller HID over I2C Standard Mode Serial Clock Line Low Period
  UINT64   ThcHidI2cStandardModeSerialDataLineTransmitHoldPeriod[2]; ///< Offset 1043    Touch Host Controller HID over I2C Standard Mode Serial Data Line Transmit Hold Period
  UINT64   ThcHidI2cStandardModeSerialDataLineReceiveHoldPeriod[2]; ///< Offset 1059    Touch Host Controller HID over I2C Standard Mode Serial Data Receive Hold Period
  UINT64   ThcHidI2cFastModeSerialClockLineHighPeriod[2]; ///< Offset 1075    Touch Host Controller HID over I2C Fast Mode Serial Clock Line High Period
  UINT64   ThcHidI2cFastModeSerialClockLineLowPeriod[2]; ///< Offset 1091    Touch Host Controller HID over I2C Fast Mode Serial Clock Line Low Period
  UINT64   ThcHidI2cFastModeSerialDataLineTransmitHoldPeriod[2]; ///< Offset 1107    Touch Host Controller HID over I2C Fast Mode Serial Data Line Transmit Hold Period
  UINT64   ThcHidI2cFastModeSerialDataLineReceiveHoldPeriod[2]; ///< Offset 1123    Touch Host Controller HID over I2C Fast Mode Serial Data Line Receive Hold Period
  UINT64   ThcHidI2cMaxSuppressedSpikesSMFMFMP[2];  ///< Offset 1139    Touch Host Controller HID over I2C Maximum Length Of Suppressed Spikes In Std Mode Fast Mode And Fast Mode Plus
  UINT64   ThcHidI2cFastModePlusSerialClockLineHighPeriod[2]; ///< Offset 1155    Touch Host Controller HID over I2C Fast Mode Plus Serial Clock Line High Period
  UINT64   ThcHidI2cFastModePlusSerialClockLineLowPeriod[2]; ///< Offset 1171    Touch Host Controller HID over I2C Fast Mode Plus Serial Clock Line Low Period
  UINT64   ThcHidI2cFastModePlusSerialDataLineTransmitHoldPeriod[2]; ///< Offset 1187    Touch Host Controller HID over I2C Fast Mode Plus Serial Data Line Transmit Hold Period
  UINT64   ThcHidI2cFastModePlusSerialDataLineReceiveHoldPeriod[2]; ///< Offset 1203    Touch Host Controller HID over I2C Fast Mode Plus Serial Data Line Receive Hold Period
  UINT64   ThcHidI2cHighSpeedModePlusSerialClockLineHighPeriod[2]; ///< Offset 1219    Touch Host Controller HID over I2C High Speed Mode Plus Serial Clock Line High Period
  UINT64   ThcHidI2cHighSpeedModePlusSerialClockLineLowPeriod[2]; ///< Offset 1235    Touch Host Controller HID over I2C High Speed Mode Plus Serial Clock Line Low Period
  UINT64   ThcHidI2cHighSpeedModePlusSerialDataLineTransmitHoldPeriod[2]; ///< Offset 1251    Touch Host Controller HID over I2C High Speed Mode Plus Serial Data Line Transmit Hold Period
  UINT64   ThcHidI2cHighSpeedModePlusSerialDataLineReceiveHoldPeriod[2]; ///< Offset 1267    Touch Host Controller HID over I2C High Speed Mode Plus Serial Data Line Receive Hold Period
  UINT64   ThcHidI2cMaximumLengthOfSuppressedSpikesInHighSpeedMode[2]; ///< Offset 1283    Touch Host Controller HID over I2C Maximum Length Of Suppressed Spikes In High Speed Mode
  UINT16   ThcHidI2cDeviceDescriptorAddress[2];     ///< Offset 1299    Touch Host Controller HID over I2C Device Descriptor Address
  UINT8    CppmFaEn;                                ///< Offset 1303    CPPM Forced Alignment Enable
  UINT8    PchAttached;                             ///< Offset 1304    PCH Attached
  UINT8    ThcWakeIntEdgeLevel[2];                  ///< Offset 1305    THC Wake Interrupt Edge Level
  UINT8    ThcWakeIntActiveLevel[2];                ///< Offset 1307    THC Wake Interrupt Active Level
  UINT8    ThcWakeIntPinConfig[2];                  ///< Offset 1309    THC Wake Interrupt Pin Config
  UINT8    SML0;                                    ///< Offset 1311    HD-Audio SoundWire Link #1 Multilane lanes enabled
  UINT8    SML1;                                    ///< Offset 1312    HD-Audio SoundWire Link #2 Multilane lanes enabled
  UINT8    SML2;                                    ///< Offset 1313    HD-Audio SoundWire Link #3 Multilane lanes enabled
  UINT8    SML3;                                    ///< Offset 1314    HD-Audio SoundWire Link #4 Multilane lanes enabled
  UINT8    SML4;                                    ///< Offset 1315    HD-Audio SoundWire Link #5 Multilane lanes enabled
  UINT8    DtrSciEnable;                            ///< Offset 1316    PMC DTR SCI enable
  UINT8    SWCS;                                    ///< Offset 1317    SoundWire Clock Source Select
  UINT8    SSF0;                                    ///< Offset 1318    SoundWire Supported Frequency Pool Link #0
  UINT8    GlobalPcieAer;                           ///< Offset 1319    Global PCIe Advanced Error Reporting
  UINT64   ThcHidI2cMaxFrameSize[2];                ///< Offset 1320    Touch Host Controller HID over I2C Max Frame size Enable
  UINT64   ThcHidI2cMaxFrameSizeValue[2];           ///< Offset 1336    Touch Host Controller HID over I2C Max Frame size value
  UINT64   ThcHidI2cIntDelay[2];                    ///< Offset 1352    Touch Host Controller HID over I2C Interrupt delay Enable
  UINT64   ThcHidI2cIntDelayValue[2];               ///< Offset 1368    Touch Host Controller HID over I2C Interrupt delay value
  UINT8    DFS0;                                    ///< Offset 1384    HD-Audio SoundWire Link #1 Dynamic Frame Shape
  UINT8    DFS1;                                    ///< Offset 1385    HD-Audio SoundWire Link #2 Dynamic Frame Shape
  UINT8    DFS2;                                    ///< Offset 1386    HD-Audio SoundWire Link #3 Dynamic Frame Shape
  UINT8    DFS3;                                    ///< Offset 1387    HD-Audio SoundWire Link #4 Dynamic Frame Shape
  UINT8    DFS4;                                    ///< Offset 1388    HD-Audio SoundWire Link #5 Dynamic Frame Shape
  UINT16   FRS0;                                    ///< Offset 1389    HD-Audio SoundWire Link #1 Frame Row Size
  UINT16   FRS1;                                    ///< Offset 1391    HD-Audio SoundWire Link #2 Frame Row Size
  UINT16   FRS2;                                    ///< Offset 1393    HD-Audio SoundWire Link #3 Frame Row Size
  UINT16   FRS3;                                    ///< Offset 1395    HD-Audio SoundWire Link #4 Frame Row Size
  UINT16   FRS4;                                    ///< Offset 1397    HD-Audio SoundWire Link #5 Frame Row Size
  UINT8    FCS0;                                    ///< Offset 1399    HD-Audio SoundWire Link #1 Frame Col Size
  UINT8    FCS1;                                    ///< Offset 1400    HD-Audio SoundWire Link #2 Frame Col Size
  UINT8    FCS2;                                    ///< Offset 1401    HD-Audio SoundWire Link #3 Frame Col Size
  UINT8    FCS3;                                    ///< Offset 1402    HD-Audio SoundWire Link #4 Frame Col Size
  UINT8    FCS4;                                    ///< Offset 1403    HD-Audio SoundWire Link #5 Frame Col Size
  UINT8    SSF1;                                    ///< Offset 1404    SoundWire Supported Frequency Pool Link #1
  UINT8    SSF2;                                    ///< Offset 1405    SoundWire Supported Frequency Pool Link #2
  UINT8    SSF3;                                    ///< Offset 1406    SoundWire Supported Frequency Pool Link #3
  UINT8    SSF4;                                    ///< Offset 1407    SoundWire Supported Frequency Pool Link #4
} PCH_NVS_AREA;

#pragma pack(pop)
#endif
