//
// Automatically generated by GenNvs ver 2.4.7
// Please DO NOT modify !!!
//


/** @file
  ACPI DSDT table

  Copyright (c) 2026, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

  // Define a Global region of ACPI NVS Region that may be used for any
  // type of implementation.  The starting offset and size will be fixed
  // up by the System BIOS during POST.  Note that the Size must be a word
  // in size to be fixed up correctly.

#ifndef _PLATFORM_NVS_AREA_DEF_H_
#define _PLATFORM_NVS_AREA_DEF_H_

#pragma pack (push,1)
typedef struct {
  //
  // Miscellaneous Dynamic Registers:
  //
  UINT16   OperatingSystem;                         ///< Offset 0       Operating System
  UINT8    SmiFunction;                             ///< Offset 2       SMI Function Call (ASL to SMI via I/O Trap)
  UINT8    SmiParameter0;                           ///< Offset 3       SMIF - Parameter 0
  UINT8    SmiParameter1;                           ///< Offset 4       SMIF - Parameter 1
  UINT8    SciFunction;                             ///< Offset 5       SCI Function Call (SMI to ASL via _L00)
  UINT8    SciParameter0;                           ///< Offset 6       SCIF - Parameter 0
  UINT8    SciParameter1;                           ///< Offset 7       SCIF - Parameter 1
  UINT8    GlobalLock;                              ///< Offset 8       Global Lock Function Call (EC Communication)
  UINT8    LockParameter0;                          ///< Offset 9       LCKF - Parameter 0
  UINT8    LockParameter1;                          ///< Offset 10      LCKF - Parameter 1
  UINT8    PowerState;                              ///< Offset 11      Power State (AC Mode = 1)
  UINT8    DebugState;                              ///< Offset 12      Debug State
  //
  // Thermal Policy Registers:
  //
  UINT8    EnableThermalKSC;                        ///< Offset 13      Enable Thermal Offset for KSC
  UINT8    Ac1TripPoint;                            ///< Offset 14      Active Trip Point 1
  UINT8    Ac0TripPoint;                            ///< Offset 15      Active Trip Point
  UINT8    PassiveThermalTripPoint;                 ///< Offset 16      Passive Trip Point
  UINT8    PassiveTc1Value;                         ///< Offset 17      Passive Trip Point TC1 Value
  UINT8    PassiveTc2Value;                         ///< Offset 18      Passive Trip Point TC2 Value
  UINT8    PassiveTspValue;                         ///< Offset 19      Passive Trip Point TSP Value
  UINT8    CriticalThermalTripPoint;                ///< Offset 20      Critical Trip Point
  //
  // Revision Field:
  //
  UINT8    Revision;                                ///< Offset 21      Revison of GlobalNvsArea
  //
  // CPU Identification Registers:
  //
  UINT8    ApicEnable;                              ///< Offset 22      APIC Enabled by SBIOS (APIC Enabled = 1)
  UINT8    ThreadCount;                             ///< Offset 23      Number of Enabled Threads
  UINT8    CurentPdcState0;                         ///< Offset 24      PDC Settings, Processor 0
  UINT8    CurentPdcState1;                         ///< Offset 25      PDC Settings, Processor 1
  UINT8    MaximumPpcState;                         ///< Offset 26      Maximum PPC state
  UINT32   PpmFlags;                                ///< Offset 27      PPM Flags (Same as CFGD)
  UINT8    C6C7Latency;                             ///< Offset 31      C6/C7 Entry/Exit latency
  //
  // Extended Mobile Access Values
  //
  UINT8    EmaEnable;                               ///< Offset 32      EMA Enable
  UINT16   EmaPointer;                              ///< Offset 33      EMA Pointer
  UINT16   EmaLength;                               ///< Offset 35      EMA Length
  //
  // Virtual Dock Status:
  //
  UINT8    VirtualDockStatus;                       ///< Offset 37      Virtual Dock Status
  //
  // TPM Registers
  //
  UINT8    MorData;                                 ///< Offset 38      Memory Overwrite Request Data
  UINT8    TcgParamter;                             ///< Offset 39      Used for save the Mor and/or physical presence paramter
  UINT32   PPResponse;                              ///< Offset 40      Physical Presence request operation response
  UINT8    PPRequest;                               ///< Offset 44      Physical Presence request operation
  UINT8    LastPPRequest;                           ///< Offset 45      Last Physical Presence request operation
  //
  // SATA Registers:
  //
  UINT8    IdeMode;                                 ///< Offset 46      IDE Mode (Compatible\Enhanced)
  //
  // Board Id
  //
  UINT8    PlatformBoardId;                         ///< Offset 47      Platform Board id
  UINT8    BoardType;                               ///< Offset 48      Board Type
  //
  // PCIe Hot Plug
  //
  UINT8    PcieOSCControl;                          ///< Offset 49      PCIE OSC Control
  UINT8    NativePCIESupport;                       ///< Offset 50      Native PCIE Setup Value
  //
  // USB Sideband Deferring Support
  //
  UINT8    HostAlertVector1;                        ///< Offset 51      USB Sideband Deferring GPE Vector (HOST_ALERT#1)
  UINT8    HostAlertVector2;                        ///< Offset 52      USB Sideband Deferring GPE Vector (HOST_ALERT#2)
  //
  // Embedded Controller Availability Flag.
  //
  UINT8    EcAvailable;                             ///< Offset 53      Embedded Controller Availability Flag.
  //
  // Global Variables
  //
  UINT8    DisplaySupportFlag;                      ///< Offset 54      _DOS Display Support Flag.
  UINT8    InterruptModeFlag;                       ///< Offset 55      Global IOAPIC/8259 Interrupt Mode Flag.
  UINT8    CoolingTypeFlag;                         ///< Offset 56      Global Cooling Type Flag.
  UINT8    L01Counter;                              ///< Offset 57      Global L01 Counter.
  UINT8    VirtualFan0Status;                       ///< Offset 58      Virtual Fan0 Status.
  UINT8    VirtualFan1Status;                       ///< Offset 59      Virtual Fan1 Status.
  UINT8    VirtualFan2Status;                       ///< Offset 60      Virtual Fan2 Status.
  UINT8    VirtualFan3Status;                       ///< Offset 61      Virtual Fan3 Status.
  UINT8    VirtualFan4Status;                       ///< Offset 62      Virtual Fan4 Status.
  UINT8    VirtualFan5Status;                       ///< Offset 63      Virtual Fan5 Status.
  UINT8    VirtualFan6Status;                       ///< Offset 64      Virtual Fan6 Status.
  UINT8    VirtualFan7Status;                       ///< Offset 65      Virtual Fan7 Status.
  UINT8    VirtualFan8Status;                       ///< Offset 66      Virtual Fan8 Status.
  UINT8    VirtualFan9Status;                       ///< Offset 67      Virtual Fan9 Status.
  //
  // Thermal
  //
  UINT32   PlatformCpuId;                           ///< Offset 68      CPUID Feature Information [EAX]
  UINT32   TBARB;                                   ///< Offset 72      Reserved for Thermal Base Low Address for BIOS
  UINT32   TBARBH;                                  ///< Offset 76      Reserved for Thermal Base High Address for BIOS
  UINT8    TsOnDimmEnabled;                         ///< Offset 80      TS-on-DIMM is chosen in SETUP and present on the DIMM
  //
  // Board info
  //
  UINT8    PlatformFlavor;                          ///< Offset 81      Platform Flavor
  UINT16   BoardRev;                                ///< Offset 82      Board Rev
  //
  // Package temperature
  //
  UINT8    PeciAccessMethod;                        ///< Offset 84      Peci Access Method
  UINT8    Ac0FanSpeed;                             ///< Offset 85      _AC0 Fan Speed
  UINT8    Ac1FanSpeed;                             ///< Offset 86      _AC1 Fan Speed
  //
  // XTU 3.0 Specification
  //
  UINT32   XTUBaseAddress;                          ///< Offset 87      XTU Continous structure Base Address
  UINT32   XTUSize;                                 ///< Offset 91      XMP Size
  UINT32   XMPBaseAddress;                          ///< Offset 95      XMP Base Address
  UINT8    DDRReferenceFreq;                        ///< Offset 99      DDR Reference Frequency
  UINT8    Rtd3Support;                             ///< Offset 100     Runtime D3 support.
  UINT8    Rtd3P0dl;                                ///< Offset 101     User selctable Delay for Device D0 transition.
  UINT8    Rtd3P3dl;                                ///< Offset 102     User selctable Delay for Device D3 transition.
  UINT8    Rtd3Pcie;                                ///< Offset 103     RTD3 Support for PCIe
  UINT8    LowPowerS0Idle;                          ///< Offset 104     Low Power S0 Idle Enable
  UINT8    PuisEnable;                              ///< Offset 105     Power Up In Standby mode
  //
  // BIOS only version of Config TDP
  //
  UINT8    ConfigTdpBios;                           ///< Offset 106     enable/disable BIOS only version of Config TDP
  UINT8    DockSmi;                                 ///< Offset 107     Dock SMI number
  UINT8    Reserved0[391];                          ///< Offset 108:498
  UINT8    PseudoG3State;                           ///< Offset 499     Pseudo G3 Enable / Disable
  UINT8    Rtd3I2C0SensorHub;                       ///< Offset 500     RTD3 support for I2C0 SH
  UINT8    VirtualGpioButtonSxBitmask;              ///< Offset 501     Virtual GPIO button Notify Sleep State Change
  UINT16   Rtd3AudioDelay;                          ///< Offset 502     RTD3 Audio Codec device delay
  UINT16   Rtd3TouchPadDelay;                       ///< Offset 504     RTD3 TouchPad delay time after applying power to device
  UINT16   Rtd3TouchPanelDelay;                     ///< Offset 506     RTD3 TouchPanel delay time after applying power to device
  UINT16   Rtd3SensorHub;                           ///< Offset 508     RTD3 SensorHub delay time after applying power to device
  UINT16   VRRampUpDelay;                           ///< Offset 510     VR Ramp up delay
  UINT8    PstateCapping;                           ///< Offset 512     P-state Capping
  UINT16   Rtd3I2C0ControllerPS0Delay;              ///< Offset 513     Delay in _PS0 after powering up I2C0 Controller
  UINT16   Rtd3I2C1ControllerPS0Delay;              ///< Offset 515     Delay in _PS0 after powering up I2C1 Controller
  UINT16   Rtd3Config0;                             ///< Offset 517     RTD3 Config Setting0(BIT0:ZPODD, BIT1:Reserved, BIT2:PCIe NVMe, BIT3:BT, BIT4:SKL SDS SIP I2C Touch, BIT6:Card Reader)
  UINT8    Ps2MouseEnable;                          ///< Offset 519     Ps2 Mouse Enable
  UINT8    ScanMatrixEnable;                        ///< Offset 520     Scan Matrix Keyboard Support Enable
  UINT16   SSH0;                                    ///< Offset 521     SSCN-HIGH for I2C0
  UINT16   SSL0;                                    ///< Offset 523     SSCN-LOW  for I2C0
  UINT16   SSD0;                                    ///< Offset 525     SSCN-HOLD for I2C0
  UINT16   FMH0;                                    ///< Offset 527     FMCN-HIGH for I2C0
  UINT16   FML0;                                    ///< Offset 529     FMCN-LOW  for I2C0
  UINT16   FMD0;                                    ///< Offset 531     FMCN-HOLD for I2C0
  UINT16   FPH0;                                    ///< Offset 533     FPCN-HIGH for I2C0
  UINT16   FPL0;                                    ///< Offset 535     FPCN-LOW  for I2C0
  UINT16   FPD0;                                    ///< Offset 537     FPCN-HOLD for I2C0
  UINT16   HSH0;                                    ///< Offset 539     HSCN-HIGH for I2C0
  UINT16   HSL0;                                    ///< Offset 541     HSCN-LOW  for I2C0
  UINT16   HSD0;                                    ///< Offset 543     HSCN-HOLD for I2C0
  UINT8    Reserved1[28];                           ///< Offset 545:572
  UINT16   SSH1;                                    ///< Offset 573     SSCN-HIGH for I2C1
  UINT16   SSL1;                                    ///< Offset 575     SSCN-LOW  for I2C1
  UINT16   SSD1;                                    ///< Offset 577     SSCN-HOLD for I2C1
  UINT16   FMH1;                                    ///< Offset 579     FMCN-HIGH for I2C1
  UINT16   FML1;                                    ///< Offset 581     FMCN-LOW  for I2C1
  UINT16   FMD1;                                    ///< Offset 583     FMCN-HOLD for I2C1
  UINT16   FPH1;                                    ///< Offset 585     FPCN-HIGH for I2C1
  UINT16   FPL1;                                    ///< Offset 587     FPCN-LOW  for I2C1
  UINT16   FPD1;                                    ///< Offset 589     FPCN-HOLD for I2C1
  UINT16   HSH1;                                    ///< Offset 591     HSCN-HIGH for I2C1
  UINT16   HSL1;                                    ///< Offset 593     HSCN-LOW  for I2C1
  UINT16   HSD1;                                    ///< Offset 595     HSCN-HOLD for I2C1
  UINT8    Reserved2[1];                            ///< Offset 597:597
  UINT16   SSH2;                                    ///< Offset 598     SSCN-HIGH for I2C2
  UINT16   SSL2;                                    ///< Offset 600     SSCN-LOW  for I2C2
  UINT16   SSD2;                                    ///< Offset 602     SSCN-HOLD for I2C2
  UINT16   FMH2;                                    ///< Offset 604     FMCN-HIGH for I2C2
  UINT16   FML2;                                    ///< Offset 606     FMCN-LOW  for I2C2
  UINT16   FMD2;                                    ///< Offset 608     FMCN-HOLD for I2C2
  UINT16   FPH2;                                    ///< Offset 610     FPCN-HIGH for I2C2
  UINT16   FPL2;                                    ///< Offset 612     FPCN-LOW  for I2C2
  UINT16   FPD2;                                    ///< Offset 614     FPCN-HOLD for I2C2
  UINT16   HSH2;                                    ///< Offset 616     HSCN-HIGH for I2C2
  UINT16   HSL2;                                    ///< Offset 618     HSCN-LOW  for I2C2
  UINT16   HSD2;                                    ///< Offset 620     HSCN-HOLD for I2C2
  UINT8    Reserved3[1];                            ///< Offset 622:622
  UINT16   SSH3;                                    ///< Offset 623     SSCN-HIGH for I2C3
  UINT16   SSL3;                                    ///< Offset 625     SSCN-LOW  for I2C3
  UINT16   SSD3;                                    ///< Offset 627     SSCN-HOLD for I2C3
  UINT16   FMH3;                                    ///< Offset 629     FMCN-HIGH for I2C3
  UINT16   FML3;                                    ///< Offset 631     FMCN-LOW  for I2C3
  UINT16   FMD3;                                    ///< Offset 633     FMCN-HOLD for I2C3
  UINT16   FPH3;                                    ///< Offset 635     FPCN-HIGH for I2C3
  UINT16   FPL3;                                    ///< Offset 637     FPCN-LOW  for I2C3
  UINT16   FPD3;                                    ///< Offset 639     FPCN-HOLD for I2C3
  UINT16   HSH3;                                    ///< Offset 641     HSCN-HIGH for I2C3
  UINT16   HSL3;                                    ///< Offset 643     HSCN-LOW  for I2C3
  UINT16   HSD3;                                    ///< Offset 645     HSCN-HOLD for I2C3
  UINT8    Reserved4[1];                            ///< Offset 647:647
  UINT16   SSH4;                                    ///< Offset 648     SSCN-HIGH for I2C4
  UINT16   SSL4;                                    ///< Offset 650     SSCN-LOW  for I2C4
  UINT16   SSD4;                                    ///< Offset 652     SSCN-HOLD for I2C4
  UINT16   FMH4;                                    ///< Offset 654     FMCN-HIGH for I2C4
  UINT16   FML4;                                    ///< Offset 656     FMCN-LOW  for I2C4
  UINT16   FMD4;                                    ///< Offset 658     FMCN-HOLD for I2C4
  UINT16   FPH4;                                    ///< Offset 660     FPCN-HIGH for I2C4
  UINT16   FPL4;                                    ///< Offset 662     FPCN-LOW  for I2C4
  UINT16   FPD4;                                    ///< Offset 664     FPCN-HOLD for I2C4
  UINT16   HSH4;                                    ///< Offset 666     HSCN-HIGH for I2C4
  UINT16   HSL4;                                    ///< Offset 668     HSCN-LOW  for I2C4
  UINT16   HSD4;                                    ///< Offset 670     HSCN-HOLD for I2C4
  UINT8    Reserved5[1];                            ///< Offset 672:672
  UINT16   SSH5;                                    ///< Offset 673     SSCN-HIGH for I2C5
  UINT16   SSL5;                                    ///< Offset 675     SSCN-LOW  for I2C5
  UINT16   SSD5;                                    ///< Offset 677     SSCN-HOLD for I2C5
  UINT16   FMH5;                                    ///< Offset 679     FMCN-HIGH for I2C5
  UINT16   FML5;                                    ///< Offset 681     FMCN-LOW  for I2C5
  UINT16   FMD5;                                    ///< Offset 683     FMCN-HOLD for I2C5
  UINT16   FPH5;                                    ///< Offset 685     FPCN-HIGH for I2C5
  UINT16   FPL5;                                    ///< Offset 687     FPCN-LOW  for I2C5
  UINT16   FPD5;                                    ///< Offset 689     FPCN-HOLD for I2C5
  UINT16   HSH5;                                    ///< Offset 691     HSCN-HIGH for I2C5
  UINT16   HSL5;                                    ///< Offset 693     HSCN-LOW  for I2C5
  UINT16   HSD5;                                    ///< Offset 695     HSCN-HOLD for I2C5
  UINT8    Reserved6[1];                            ///< Offset 697:697
  UINT16   M0C0;                                    ///< Offset 698     M0D3 for I2C0
  UINT16   M1C0;                                    ///< Offset 700     M1D3 for I2C0
  UINT16   M0C1;                                    ///< Offset 702     M0D3 for I2C1
  UINT16   M1C1;                                    ///< Offset 704     M1D3 for I2C1
  UINT16   M0C2;                                    ///< Offset 706     M0D3 for I2C2
  UINT16   M1C2;                                    ///< Offset 708     M1D3 for I2C2
  UINT16   M0C3;                                    ///< Offset 710     M0D3 for I2C3
  UINT16   M1C3;                                    ///< Offset 712     M1D3 for I2C3
  UINT16   M0C4;                                    ///< Offset 714     M0D3 for I2C4
  UINT16   M1C4;                                    ///< Offset 716     M1D3 for I2C4
  UINT16   M0C5;                                    ///< Offset 718     M0D3 for I2C5
  UINT16   M1C5;                                    ///< Offset 720     M1D3 for I2C5
  UINT16   M0C6;                                    ///< Offset 722     M0D3 for SPI0
  UINT16   M1C6;                                    ///< Offset 724     M1D3 for SPI0
  UINT8    Reserved7[9];                            ///< Offset 726:734
  UINT16   M0C9;                                    ///< Offset 735     M0D3 for UART0
  UINT16   M1C9;                                    ///< Offset 737     M1D3 for UART0
  UINT16   M0CA;                                    ///< Offset 739     M0D3 for UART1
  UINT16   M1CA;                                    ///< Offset 741     M1D3 for UART1
  UINT16   M0CB;                                    ///< Offset 743     M0D3 for UART2
  UINT16   M1CB;                                    ///< Offset 745     M1D3 for UART2
  UINT8    Reserved8[1];                            ///< Offset 747:747
  //
  // Driver Mode
  //
  UINT32   GpioIrqRoute;                            ///< Offset 748     GPIO IRQ
  UINT8    DriverModeTouchPanel;                    ///< Offset 752     PIRQS 34,50(GPIO)
  UINT8    DriverModeTouchPad;                      ///< Offset 753     PIRQX 39,55(GPIO)
  UINT8    DriverModeSensorHub;                     ///< Offset 754     PIRQM 28,14(GPIO)
  UINT8    SensorStandby;                           ///< Offset 755     Sensor Standby mode
  UINT8    PL1LimitCS;                              ///< Offset 756     set PL1 limit when entering CS
  UINT16   PL1LimitCSValue;                         ///< Offset 757     PL1 limit value
  UINT8    EnableCpuVrTempSensorDevice;             ///< Offset 759     EnableCpuVrTempSensorDevice
  UINT8    EnableSsdTempSensorDevice;               ///< Offset 760     EnableSsdTempSensorDevice
  UINT8    EnableInletFanTempSensorDevice;          ///< Offset 761     EnableInletFanTempSensorDevice
  UINT8    ActiveThermalTripPointInletFan;          ///< Offset 762     ActiveThermalTripPointInletFan
  UINT8    PassiveThermalTripPointInletFan;         ///< Offset 763     PassiveThermalTripPointInletFan
  UINT8    CriticalThermalTripPointInletFan;        ///< Offset 764     CriticalThermalTripPointInletFan
  UINT8    HotThermalTripPointInletFan;             ///< Offset 765     HotThermalTripPointInletFan
  UINT8    UsbSensorHub;                            ///< Offset 766     Sensor Hub Type - (0)None, (1)USB, (2)I2C Intel, (3)I2C STM
  UINT8    BCV4;                                    ///< Offset 767     Broadcom's Bluetooth adapter's revision
  UINT8    WTV0;                                    ///< Offset 768     I2C0/WITT devices version
  UINT8    WTV1;                                    ///< Offset 769     I2C1/WITT devices version
  UINT8    AtmelPanelFwUpdate;                      ///< Offset 770     Atmel panel FW update Enable/Disable
  UINT8    Reserved9[7];                            ///< Offset 771:777
  UINT64   LowPowerS0IdleConstraint;                ///< Offset 778     PEP Constraints
  // Bit[1:0] - Storage (0:None, 1:Storage Controller, 2:Raid)
  // Bit[2]   - En/Dis UART0
  // Bit[3]   - En/Dis UART1
  // Bit[4]   - En/Dis I2C0
  // Bit[5]   - En/Dis I2C1
  // Bit[6]   - En/Dis XHCI
  // Bit[8:7] - HD Audio (includes ADSP) (0: No Constraints or 1: D0/F1 or 3:D3)
  // Bit[9]   - En/Dis Gfx
  // Bit[10]  - En/Dis CPU
  // Bit[11]  - En/Dis EMMC
  // Bit[12]  - En/Dis SDXC
  // Bit[13]  - En/Dis I2C2
  // Bit[14]  - En/Dis I2C3
  // Bit[15]  - En/Dis I2C4
  // Bit[16]  - En/Dis I2C5
  // Bit[17]  - En/Dis UART2
  // Bit[18]  - En/Dis SPI0
  // Bit[19]  - En/Dis SPI1
  // Bit[20]  - En/Dis SPI2
  // Bit[21]  - En/Dis IPU0
  // Bit[22]  - En/Dis CSME
  // Bit[23]  - En/Dis LAN(GBE)
  // Bit[24]  - Reserved
  // Bit[25]  - En/Dis THC0
  // Bit[26]  - En/Dis THC1
  // Bit[27]  - Reserved
  // Bit[28]  - En/Dis I2C6
  // Bit[29]  - En/Dis TCSS IPs
  // Bit[31]  - En/Dis VMD0
  // Bit[32]  - En/Dis HECI3
  // Bit[34:33]  - PCIe Storage RP(0: No Constraints or 1: D0/F1 or 3:D3)
  // Bit[36:35] - Pcie Lan (0:No Constraint or 1:D0/F1 or 3:D3)
  // Bit[38:37] - Pcie Wlan (0:No Constraint or 1:D0/F1 or 3:D3)
  // Bit[40:39] - Pcie Gfx (0:No Constraint or 1:D0/F1 or 3:D3)
  // Bit[42:41] - Pcie Other (0:No Constraint or 1:D0/F1 or 3:D3)
  // Bit[43]  - En/Dis DG on x8 PEG port (PEG1)
  // Bit[44]  - En/Dis NPU0
  // BIT[45]  - En/Dis UFS0
  // BIT[46]  - En/Dis UFS1
  UINT16   VRStaggeringDelay;                       ///< Offset 786     VR Staggering delay
  UINT8    TenSecondPowerButtonEnable;              ///< Offset 788     10sec Power button support
  // Bit0: 10 sec P-button Enable/Disable
  // Bit1: Internal Flag
  // Bit2: Rotation Lock flag, 0:unlock, 1:lock
  // Bit3: Slate/Laptop Mode Flag, 0: Slate, 1: Laptop
  // Bit4: Undock / Dock Flag, 0: Undock, 1: Dock
  // Bit5: VBDL Flag. 0: VBDL is not called, 1: VBDL is called, Virtual Button Driver is loaded.
  // Bit7-6: Reserved for future use.
  //
  // Generation Id(Tock/Tick)
  //
  UINT8    GenerationId;                            ///< Offset 789     Generation Id(0=Shark bay, 1=Crescent Bay)
  UINT8    Reserved10[10];                          ///< Offset 790:799
  UINT32   AuxPowerLimit;                           ///< Offset 800     Maximum aux power available for PCIe root ports
  UINT8    EnumerateSataPortConstraints;            ///< Offset 804     Set to indicate to PEP that constraints at SATA ports should be enumerated
  UINT8    Reserved11[213];                         ///< Offset 805:1017
  UINT8    EnableAPPolicy;                          ///< Offset 1018    Adaptive Performance Policy @deprecated. Intel(R) Dynamic Tuning can dynamically enable/disable policies
  //
  // Intel Serial(R) IO Sensor Device Selection
  //
  UINT8    SDS0;                                    ///< Offset 1019    SerialIo Devices for controller0
  UINT8    SDS1;                                    ///< Offset 1020    SerialIo Devices for controller1
  UINT8    SDS2;                                    ///< Offset 1021    SerialIo Devices for controller2
  UINT8    SDS3;                                    ///< Offset 1022    SerialIo Devices for controller3
  UINT8    SDS4;                                    ///< Offset 1023    SerialIo Devices for controller4
  UINT8    SDS5;                                    ///< Offset 1024    SerialIo Devices for controller5
  UINT8    SDS6;                                    ///< Offset 1025    SerialIo Devices for controller6
  UINT8    SDS7;                                    ///< Offset 1026    SerialIo Devices for controller7
  UINT8    SDS8;                                    ///< Offset 1027    SerialIo Devices for controller8
  UINT8    SDS9;                                    ///< Offset 1028    SerialIo Devices for controller9
  UINT8    SDSA;                                    ///< Offset 1029    SerialIo Devices for controller10
  UINT8    TPLT;                                    ///< Offset 1030    I2C SerialIo Devices Type of TouchPanel
  UINT8    TPLM;                                    ///< Offset 1031    I2C SerialIo Devices Interrupt Mode for TouchPanel
  UINT8    TPLB;                                    ///< Offset 1032    I2C Custom TouchPanel's BUS Address
  UINT16   TPLH;                                    ///< Offset 1033    I2C Custom TouchPanel's HID Address
  UINT8    TPLS;                                    ///< Offset 1035    I2C Custom TouchPanel's BUS Speed
  UINT8    TPDT;                                    ///< Offset 1036    I2C SerialIo Devices Type of TouchPad
  UINT8    TPDM;                                    ///< Offset 1037    I2C SerialIo Devices Interrupt Mode for TouchPad
  UINT8    TPDB;                                    ///< Offset 1038    I2C Custom TouchPad's BUS Address
  UINT16   TPDH;                                    ///< Offset 1039    I2C Custom TouchPad's HID Address
  UINT8    TPDS;                                    ///< Offset 1041    I2C Custom TouchPad's BUS Speed
  UINT8    WTVX;                                    ///< Offset 1042    WITT test devices' version
  UINT8    WITX;                                    ///< Offset 1043    WITT test devices' connection point
  UINT8    GPTD;                                    ///< Offset 1044    GPIO test devices
  UINT16   GDBT;                                    ///< Offset 1045    GPIO test devices' debounce value,
  UINT8    UTKX;                                    ///< Offset 1047    UTK test devices' connection point
  UINT8    SPTD;                                    ///< Offset 1048    SerialIo additional test devices
  UINT8    Reserved12[17];                          ///< Offset 1049:1065
  UINT32   TableLoadBuffer;                         ///< Offset 1066    Buffer for runtime ACPI Table loading
  UINT8    SDM0;                                    ///< Offset 1070    interrupt mode for controller0 devices
  UINT8    SDM1;                                    ///< Offset 1071    interrupt mode for controller1 devices
  UINT8    SDM2;                                    ///< Offset 1072    interrupt mode for controller2 devices
  UINT8    SDM3;                                    ///< Offset 1073    interrupt mode for controller3 devices
  UINT8    SDM4;                                    ///< Offset 1074    interrupt mode for controller4 devices
  UINT8    SDM5;                                    ///< Offset 1075    interrupt mode for controller5 devices
  UINT8    SDM6;                                    ///< Offset 1076    interrupt mode for controller6 devices
  UINT8    SDM7;                                    ///< Offset 1077    interrupt mode for controller7 devices
  UINT8    SDM8;                                    ///< Offset 1078    interrupt mode for controller8 devices
  UINT8    SDM9;                                    ///< Offset 1079    interrupt mode for controller9 devices
  UINT8    SDMA;                                    ///< Offset 1080    interrupt mode for controller10 devices
  UINT8    SDMB;                                    ///< Offset 1081    interrupt mode for controller11 devices
  UINT8    Reserved13[1];                           ///< Offset 1082:1082
  UINT8    USTP;                                    ///< Offset 1083    use SerialIo timing parameters
  UINT8    Reserved14[41];                          ///< Offset 1084:1124
  UINT32   TouchpadIrqGpio;                         ///< Offset 1125    Gpio for touchPaD Interrupt
  UINT32   TouchpanelIrqGpio;                       ///< Offset 1129    Gpio for touchPaneL Interrupt
  UINT8    PciDelayOptimizationEcr;                 ///< Offset 1133
  UINT8    I2SC;                                    ///< Offset 1134    HD Audio I2S Codec Selection
  UINT32   I2SI;                                    ///< Offset 1135    HD Audio I2S Codec Interrupt Pin
  UINT8    I2SB;                                    ///< Offset 1139    HD Audio I2S Codec Connection to I2C bus controller instance (I2C[0-5])
  UINT8    WirelessCharging;                        ///< Offset 1140    WirelessCharging
  UINT8    Reserved15[1015];                        ///< Offset 1141:2155
  UINT32   HdaDspPpModuleMask;                      ///< Offset 2156    HD-Audio DSP Post-Processing Module Mask
  UINT64   HdaDspPpModCustomGuid1Low;               ///< Offset 2160    HDA PP module custom GUID 1 - first 64bit  [0-63]
  UINT64   HdaDspPpModCustomGuid1High;              ///< Offset 2168    HDA PP module custom GUID 1 - second 64bit [64-127]
  UINT64   HdaDspPpModCustomGuid2Low;               ///< Offset 2176    HDA PP module custom GUID 2 - first 64bit  [0-63]
  UINT64   HdaDspPpModCustomGuid2High;              ///< Offset 2184    HDA PP module custom GUID 2 - second 64bit [64-127]
  UINT64   HdaDspPpModCustomGuid3Low;               ///< Offset 2192    HDA PP module custom GUID 3 - first 64bit  [0-63]
  UINT64   HdaDspPpModCustomGuid3High;              ///< Offset 2200    HDA PP module custom GUID 3 - second 64bit [64-127]
  UINT8    HidEventFilterEnable;                    ///< Offset 2208    HID Event Filter Driver enable
  UINT8    XdciFnEnable;                            ///< Offset 2209    XDCI Enable/Disable status
  UINT8    EnableVoltageMargining;                  ///< Offset 2210    Enable Voltage Margining
  UINT16   DStateHSPort;                            ///< Offset 2211    D-State for xHCI HS port(BIT0:USB HS Port0 ~ BIT15:USB HS Port15)
  UINT16   DStateSSPort;                            ///< Offset 2213    D-State for xHCI SS port(BIT0:USB SS Port0 ~ BIT15:USB SS Port15)
  UINT8    DStateSataPort;                          ///< Offset 2215    D-State for SATA port(BIT0:SATA Port0 ~ BIT7:SATA Port7)
  UINT8    RunTimeVmControl;                        ///< Offset 2216    RunTime VM Control
  //
  //Feature Specific Data Bits
  //
  UINT8    UsbTypeCSupport;                         ///< Offset 2217    USB Type C Supported
  UINT32   HebcValue;                               ///< Offset 2218    HebcValue
  UINT8    PcdTsOnDimmTemperature;                  ///< Offset 2222    TS-on-DIMM temperature
  UINT8    Reserved16[116];                         ///< Offset 2223:2338
  UINT8    LchSupport;                              ///< Offset 2339    To enable/disable Lch
  UINT8    LchTestDevice;                           ///< Offset 2340    To enable/disable Lch TestDevice
  UINT32   LchIrqGpioPin;                           ///< Offset 2341    Lch Host Interrupt/IRQ pin
  UINT32   LchResetGpioPin;                         ///< Offset 2345    Lch Reset pin
  UINT8    PcdMipiCamSensor;                        ///< Offset 2349    Mipi Camera Sensor
  UINT8    PcdEcUart;                               ///< Offset 2350    EC UART
  UINT8    PcdZPoddConfig;                          ///< Offset 2351    ZPODD
  UINT8    PcdRGBCameraAdr;                         ///< Offset 2352    RGB Camera Address
  UINT8    PcdDepthCameraAdr;                       ///< Offset 2353    Depth Camera Addresy
  UINT8    PcdConvertableDockSupport;               ///< Offset 2354    Convertable Dock Support
  UINT8    PcdVirtualGpioButtonSupport;             ///< Offset 2355    Virtual Button Support
  UINT8    PcdAcpiEnableAllButtonSupport;           ///< Offset 2356    Acpi Enable All Button Support
  UINT8    PcdAcpiHidDriverButtonSupport;           ///< Offset 2357    Acpi Hid Driver Button Support
  //
  // UCMC setup option, GPIO Pad
  //
  UINT8    UCMS;                                    ///< Offset 2358    Option to select UCSI Version
  UINT32   UcmcPort1Gpio;                           ///< Offset 2359    Gpio for UCMC Port 1 Interrupt
  UINT32   UcmcPort2Gpio;                           ///< Offset 2363    Gpio for UCMC Port 2 Interrupt
  UINT8    Reserved17[10];                          ///< Offset 2367:2376
  UINT8    Ufp2DfpGlobalFlag;                       ///< Offset 2377    Upstream Facing port or Downstream Facing port Global Flag from LPC EC
  UINT8    Ufp2DfpUsbPort;                          ///< Offset 2378    Upstream Facing port or Downstream Facing port number from LPC EC
  UINT8    DbcGlobalFlag;                           ///< Offset 2379    Debug Mode Global Flag from LPC EC
  UINT8    DbcUsbPort;                              ///< Offset 2380    Debug Mode USB Port Number from LPC EC
  UINT8    SystemTimeAndAlarmSource;                ///< Offset 2381    Select source for System time and alarm
  UINT32   WwanPerstGpio;                           ///< Offset 2382    WWAN PERST Gpio pin
  UINT8    PcieSlot1RpNumber;                       ///< Offset 2386    Pcie Slot 1 Root Port Number
  UINT32   PcieSlot1PowerEnableGpio;                ///< Offset 2387    Pcie Slot 1 Power Enable Gpio pin
  UINT8    PcieSlot1PowerEnableGpioPolarity;        ///< Offset 2391    Pcie Slot 1 Power Enable Gpio pin polarity
  UINT32   PcieSlot1RstGpio;                        ///< Offset 2392    Pcie Slot 1 Rest Gpio pin
  UINT8    PcieSlot1RstGpioPolarity;                ///< Offset 2396    Pcie Slot 1 Rest Gpio pin polarity
  UINT8    PcieSlot2RpNumber;                       ///< Offset 2397    Pcie Slot 2 Root Port Number
  UINT32   PcieSlot2PowerEnableGpio;                ///< Offset 2398    Pcie Slot 2 Power Enable Gpio pin
  UINT8    PcieSlot2PowerEnableGpioPolarity;        ///< Offset 2402    Pcie Slot 2 Power Enable Gpio pin polarity
  UINT32   PcieSlot2RstGpio;                        ///< Offset 2403    Pcie Slot 2 Rest Gpio pin
  UINT8    PcieSlot2RstGpioPolarity;                ///< Offset 2407    Pcie Slot 2 Rest Gpio pin polarity
  UINT8    PcieSlot3RpNumber;                       ///< Offset 2408    Pcie Slot 3 Root Port Number
  UINT32   PcieSlot3PowerEnableGpio;                ///< Offset 2409    Pcie Slot 3 Power Enable Gpio pin
  UINT8    PcieSlot3PowerEnableGpioPolarity;        ///< Offset 2413    Pcie Slot 3 Power Enable Gpio pin polarity
  UINT32   PcieSlot3RstGpio;                        ///< Offset 2414    Pcie Slot 3 Rest Gpio pin
  UINT8    PcieSlot3RstGpioPolarity;                ///< Offset 2418    Pcie Slot 3 Rest Gpio pin polarity
  UINT8    PcieSlot4RpNumber;                       ///< Offset 2419    Pcie Slot 4 Root Port Number
  UINT32   PcieSlot4PowerEnableGpio;                ///< Offset 2420    Pcie Slot 4 Power Enable Gpio pin
  UINT8    PcieSlot4PowerEnableGpioPolarity;        ///< Offset 2424    Pcie Slot 4 Power Enable Gpio pin polarity
  UINT32   PcieSlot4RstGpio;                        ///< Offset 2425    Pcie Slot 4 Rest Gpio pin
  UINT8    PcieSlot4RstGpioPolarity;                ///< Offset 2429    Pcie Slot 4 Rest Gpio pin polarity
  UINT8    PcieSlot5RpNumber;                       ///< Offset 2430    Pcie Slot 5 Root Port Number
  UINT32   PcieSlot5PowerEnableGpio;                ///< Offset 2431    Pcie Slot 5 Power Enable Gpio pin
  UINT8    PcieSlot5PowerEnableGpioPolarity;        ///< Offset 2435    Pcie Slot 5 Power Enable Gpio pin polarity
  UINT32   PcieSlot5RstGpio;                        ///< Offset 2436    Pcie Slot 5 Rest Gpio pin
  UINT8    PcieSlot5RstGpioPolarity;                ///< Offset 2440    Pcie Slot 5 Rest Gpio pin polarity
  UINT8    PcieSlot6RpNumber;                       ///< Offset 2441    Pcie Slot 6 Root Port Number
  UINT32   PcieSlot6PowerEnableGpio;                ///< Offset 2442    Pcie Slot 6 Power Enable Gpio pin
  UINT8    PcieSlot6PowerEnableGpioPolarity;        ///< Offset 2446    Pcie Slot 6 Power Enable Gpio pin polarity
  UINT32   PcieSlot6RstGpio;                        ///< Offset 2447    Pcie Slot 6 Rest Gpio pin
  UINT8    PcieSlot6RstGpioPolarity;                ///< Offset 2451    Pcie Slot 6 Rest Gpio pin polarity
  UINT8    PcieSlot7RpNumber;                       ///< Offset 2452    Pcie Slot 7 Root Port Number
  UINT32   PcieSlot7PowerEnableGpio;                ///< Offset 2453    Pcie Slot 7 Power Enable Gpio pin
  UINT8    PcieSlot7PowerEnableGpioPolarity;        ///< Offset 2457    Pcie Slot 7 Power Enable Gpio pin polarity
  UINT32   PcieSlot7RstGpio;                        ///< Offset 2458    Pcie Slot 7 Rest Gpio pin
  UINT8    PcieSlot7RstGpioPolarity;                ///< Offset 2462    Pcie Slot 7 Rest Gpio pin polarity
  UINT32   WwanBbrstGpio;                           ///< Offset 2463    WWAN BBRST Gpio pin
  UINT8    TouchpadIrqGpioPolarity;                 ///< Offset 2467    TouchPaD Interrupt Gpio pin polarity
  UINT32   PchM2SsdPowerEnableGpio;                 ///< Offset 2468    Pch M.2 SSD Power Enable Gpio pin
  UINT8    PchM2SsdPowerEnableGpioPolarity;         ///< Offset 2472    Pch M.2 SSD Power Enable Gpio pin polarity
  UINT32   PchM2SsdRstGpio;                         ///< Offset 2473    Pch M.2 SSD Reset Gpio pin
  UINT8    PchM2SsdRstGpioPolarity;                 ///< Offset 2477    Pch M.2 SSD Reset Gpio pin polarity
  UINT32   M2Ssd2PowerEnableGpio;                   ///< Offset 2478    PCIe x4 M.2 SSD Power Enable Gpio pin
  UINT8    M2Ssd2PowerEnableGpioPolarity;           ///< Offset 2482    PCIe x4 M.2 SSD Power Enable Gpio pin polarity
  UINT32   M2Ssd2RstGpio;                           ///< Offset 2483    PCIe x4 M.2 SSD Reset Gpio pin
  UINT8    M2Ssd2RstGpioPolarity;                   ///< Offset 2487    PCIe x4 M.2 SSD Reset Gpio pin polarity
  UINT8    SdevXhciInterfaceNumber1;                ///< Offset 2488    SDEV xHCI Interface Number for device 1
  UINT8    SdevXhciInterfaceNumber2;                ///< Offset 2489    SDEV xHCI Interface Number for device 2
  UINT8    SdevXhciRootPortNumber1;                 ///< Offset 2490    SDEV xHCI Root Port Number for device 1
  UINT8    SdevXhciRootPortNumber2;                 ///< Offset 2491    SDEV xHCI Root Port Number for device 2
  UINT8    TsnPcsEnabled;                           ///< Offset 2492    TSN PCS device Enable
  UINT32   Dg1VramSRGpio;                           ///< Offset 2493    DG1 VRAM Self Refresh Gpio pin
  UINT32   LpmReqRegAddr;                           ///< Offset 2497    Low Power Mode required register Address
  UINT32   PegSlot1PwrEnableGpioNo;                 ///< Offset 2501    PEG slot 1 Power Enable Gpio pin
  UINT8    PegSlot1PwrEnableGpioPolarity;           ///< Offset 2505    PEG slot 1 Power Enable Gpio pin polarity
  UINT32   PegSlot1RstGpioNo;                       ///< Offset 2506    PEG slot 1 Reset Gpio pin
  UINT8    PegSlot1RootPort;                        ///< Offset 2510    PEG slot 1 Root Port
  UINT32   PegSlot2PwrEnableGpioNo;                 ///< Offset 2511    PEG slot 2 Power Enable Gpio pin
  UINT8    PegSlot2PwrEnableGpioPolarity;           ///< Offset 2515    PEG slot 2 Power Enable Gpio pin polarity
  UINT32   PegSlot2RstGpioNo;                       ///< Offset 2516    PEG slot 2 Reset Gpio pin
  UINT8    PegSlot2RootPort;                        ///< Offset 2520    PEG slot 2 Root Port
  UINT32   PchM2Ssd2PowerEnableGpio;                ///< Offset 2521    Pch M.2 SSD2 Power Enable Gpio pin
  UINT8    PchM2Ssd2PowerEnableGpioPolarity;        ///< Offset 2525    Pch M.2 SSD2 Power Enable Gpio pin polarity
  UINT32   PchM2Ssd2RstGpio;                        ///< Offset 2526    Pch M.2 SSD2 Reset Gpio pin
  UINT8    PchM2Ssd2RstGpioPolarity;                ///< Offset 2530    Pch M.2 SSD2 Reset Gpio pin polarity
  UINT32   PchM2Ssd3PowerEnableGpio;                ///< Offset 2531    Pch M.2 SSD3 Power Enable Gpio pin
  UINT8    PchM2Ssd3PowerEnableGpioPolarity;        ///< Offset 2535    Pch M.2 SSD3 Power Enable Gpio pin polarity
  UINT32   PchM2Ssd3RstGpio;                        ///< Offset 2536    Pch M.2 SSD3 Reset Gpio pin
  UINT8    PchM2Ssd3RstGpioPolarity;                ///< Offset 2540    Pch M.2 SSD3 Reset Gpio pin polarity
  UINT8    Gpe1BlockEnable;                         ///< Offset 2541    Enable GPE1
  UINT8    PmaxDevice;                              ///< Offset 2542    PMAX Device
  UINT8    PmaxAudioCodec;                          ///< Offset 2543    PMAX Audio Codec
  UINT8    PmaxWfCamera;                            ///< Offset 2544    PMAX WF Camera
  UINT8    PmaxUfCamera;                            ///< Offset 2545    PMAX UF Camera
  UINT8    PmaxFlashDevice;                         ///< Offset 2546    PMAX Flash Device
  UINT16   PcieDevOnOffDelay;                       ///< Offset 2547    PCIE Device ON/OFF Delay
  //
  // XTU SMI base address
  //
  UINT32   XtuSmiMemoryAddress;                     ///< Offset 2549    XTU SMI memory in ACPI NVS
  UINT8    WwanEnable;                              ///< Offset 2553    WWAN Enable
  UINT16   WwanTOn2ResDelayMs;                      ///< Offset 2554    FCPO# to BBRST# delay time during WWAN ON
  UINT16   WwanTOnRes2PerDelayMs;                   ///< Offset 2556    BBRST# to PERST# delay time during WWAN ON
  UINT16   WwanOemSvid;                             ///< Offset 2558    WWAN OEM SVID
  UINT16   WwanSvidTimeout;                         ///< Offset 2560    WWAN SVID Timeout
  UINT8    EnablePcieTunnelingOverUsb4;             ///< Offset 2562    Enable PCIE tunnelling support over USB4 links.
  UINT8    PreBootCmMode;                           ///< Offset 2563    USB4 CM mode information in Pre-Boot
  UINT8    CmTbtMask;                               ///< Offset 2564    Indicate enabled dTBT and iTBT for CM
  UINT8    Usb4CmSwitchEnable;                      ///< Offset 2565    USB4 CM mode switch is enabled/disabled
  UINT8    HybridGraphicsDetection;                 ///< Offset 2566    Primary Display (0=AUTO, 3=iGfx, 4=HG)
  UINT8    StorageRtd3Support;                      ///< Offset 2567    Storage Runtime D3 Support
  //
  // Data Role Swap
  //
  UINT8    UsbcDataRoleSwap;                        ///< Offset 2568    Usbc Data Role Swap
  UINT8    DeepestUSBSleepWakeCapability;           ///< Offset 2569    Deepest USB Sleep Wake Capability
  UINT64   DgBaseAddress;                           ///< Offset 2570    DG PCIe base address
  UINT32   PewakePin[12];                           ///< Offset 2578    PEWAKE Pin for Root Port 01
                                                    ///< Offset 2582    PEWAKE Pin for Root Port 02
                                                    ///< Offset 2586    PEWAKE Pin for Root Port 03
                                                    ///< Offset 2590    PEWAKE Pin for Root Port 04
                                                    ///< Offset 2594    PEWAKE Pin for Root Port 05
                                                    ///< Offset 2598    PEWAKE Pin for Root Port 06
                                                    ///< Offset 2602    PEWAKE Pin for Root Port 07
                                                    ///< Offset 2606    PEWAKE Pin for Root Port 08
                                                    ///< Offset 2610    PEWAKE Pin for Root Port 09
                                                    ///< Offset 2614    PEWAKE Pin for Root Port 10
                                                    ///< Offset 2618    PEWAKE Pin for Root Port 11
                                                    ///< Offset 2622    PEWAKE Pin for Root Port 12
  // ACPI debug NVS region
  UINT8    EnableAcpiDebug;                         ///< Offset 2626    Enable flag for ACPI debug
  UINT8    SerialPortAcpiDebug;                     ///< Offset 2627    Serial Port ACPI debug
  UINT8    SocBusBase;                              ///< Offset 2628    SoC Bus Base
  UINT8    SocBusLimit;                             ///< Offset 2629    SoC Bus Limit
  UINT16   SocIoBase;                               ///< Offset 2630    SoC IO Base
  UINT16   SocIoLimit;                              ///< Offset 2632    SoC IO Limit
  UINT32   SocMem32Base;                            ///< Offset 2634    SoC Mem32 Base
  UINT32   SocMem32Limit;                           ///< Offset 2638    SoC Mem32 Limit
  UINT64   SocMem64Base;                            ///< Offset 2642    SoC Mem64 Base
  UINT64   SocMem64Limit;                           ///< Offset 2650    SoC Mem64 Limit
  UINT8    PchBusBase;                              ///< Offset 2658    PCH Bus Base
  UINT8    PchBusLimit;                             ///< Offset 2659    PCH Bus Limit
  UINT16   PchIoBase;                               ///< Offset 2660    PCH IO Base
  UINT16   PchIoLimit;                              ///< Offset 2662    PCH IO Limit
  UINT32   PchMem32Base;                            ///< Offset 2664    PCH Mem32 Base
  UINT32   PchMem32Limit;                           ///< Offset 2668    PCH Mem32 Limit
  UINT64   PchMem64Base;                            ///< Offset 2672    PCH Mem64 Base
  UINT64   PchMem64Limit;                           ///< Offset 2680    PCH Mem64 Limit
  UINT8    SdevXhciEntry;                           ///< Offset 2688
  UINT32   DgOpRegionAddress;                       ///< Offset 2689    DG OpRegion base address
  UINT8    DgBrightnessPercentage;                  ///< Offset 2693    DG eDP Brightness Level Percentage
  //
  // I3C-0
  //
  UINT32   I3c0QueueThld;                           ///< Offset 2694    I3C0 Queue Threshold Control
  UINT32   I3c0DataBufferThld;                      ///< Offset 2698    I3C0 Data Buffer Threshold Control
  UINT32   I3c0OdTiming;                            ///< Offset 2702    I3C0 SCL I3C Open Drain Timing
  UINT32   I3c0PpTiming;                            ///< Offset 2706    I3C0 SCL I3C Push Pull Timing
  UINT32   I3c0SclI2cFmTiming;                      ///< Offset 2710    I3C0 SCL I2C Fast Mode Timing
  UINT32   I3c0SclI2cFmpTiming;                     ///< Offset 2714    I3C0 SCL I2C Fast Mode Plus Timing
  UINT32   I3c0SclI2cSsTiming;                      ///< Offset 2718    I3C0 SCL I2C Standard Speed Timing
  UINT32   I3c0ExtLcntTiming;                       ///< Offset 2722    I3C0 SCL Extended Low Count Timing
  UINT32   I3c0ExtTermLcntTiming;                   ///< Offset 2726    I3C0 SCL Termination Bit Low Count
  UINT32   I3c0SdaSwitchDelayTiming;                ///< Offset 2730    I3C0 SDA Hold and Mode Switch Delay Timing
  UINT32   I3c0BusDelayTiming;                      ///< Offset 2734    I3C0 Speed Mode Selection
  //
  // I3C-2
  //
  UINT32   I3c2QueueThld;                           ///< Offset 2738    I3C2 Queue Threshold Control
  UINT32   I3c2DataBufferThld;                      ///< Offset 2742    I3C2 Data Buffer Threshold Control
  UINT32   I3c2OdTiming;                            ///< Offset 2746    I3C2 SCL I3C Open Drain Timing
  UINT32   I3c2PpTiming;                            ///< Offset 2750    I3C2 SCL I3C Push Pull Timing
  UINT32   I3c2SclI2cFmTiming;                      ///< Offset 2754    I3C2 SCL I2C Fast Mode Timing
  UINT32   I3c2SclI2cFmpTiming;                     ///< Offset 2758    I3C2 SCL I2C Fast Mode Plus Timing
  UINT32   I3c2SclI2cSsTiming;                      ///< Offset 2762    I3C2 SCL I2C Standard Speed Timing
  UINT32   I3c2ExtLcntTiming;                       ///< Offset 2766    I3C2 SCL Extended Low Count Timing
  UINT32   I3c2ExtTermLcntTiming;                   ///< Offset 2770    I3C2 SCL Termination Bit Low Count
  UINT32   I3c2SdaSwitchDelayTiming;                ///< Offset 2774    I3C2 SDA Hold and Mode Switch Delay Timing
  UINT32   I3c2BusDelayTiming;                      ///< Offset 2778    I3C2 Speed Mode Selection
  //
  // TCSS USB3 Port
  //
  UINT8    TcssUsb3PortGroupPosition[4];            ///< Offset 2782    TCSS USB3 Port1 Group Position for _PLD
                                                    ///< Offset 2783    TCSS USB3 Port2 Group Position for _PLD
                                                    ///< Offset 2784    TCSS USB3 Port3 Group Position for _PLD
                                                    ///< Offset 2785    TCSS USB3 Port4 Group Position for _PLD
  UINT8    TcssUsb3PortVisibility[4];               ///< Offset 2786    TCSS USB3 Port1 Visibility for _PLD
                                                    ///< Offset 2787    TCSS USB3 Port2 Visibility for _PLD
                                                    ///< Offset 2788    TCSS USB3 Port3 Visibility for _PLD
                                                    ///< Offset 2789    TCSS USB3 Port4 Visibility for _PLD
  UINT8    TcssUsb3PortConnectable[4];              ///< Offset 2790    TCSS USB3 Port1 Connectable for _UPC
                                                    ///< Offset 2791    TCSS USB3 Port2 Connectable for _UPC
                                                    ///< Offset 2792    TCSS USB3 Port3 Connectable for _UPC
                                                    ///< Offset 2793    TCSS USB3 Port4 Connectable for _UPC
  UINT8    TcssUsb3PortType[4];                     ///< Offset 2794    TCSS USB3 Port1 Type for _UPC
                                                    ///< Offset 2795    TCSS USB3 Port2 Type for _UPC
                                                    ///< Offset 2796    TCSS USB3 Port3 Type for _UPC
                                                    ///< Offset 2797    TCSS USB3 Port4 Type for _UPC
  UINT8    TcssUsb3PortCapability[4];               ///< Offset 2798    TCSS USB3 Port1 Capability for _UPC
                                                    ///< Offset 2799    TCSS USB3 Port2 Capability for _UPC
                                                    ///< Offset 2800    TCSS USB3 Port3 Capability for _UPC
                                                    ///< Offset 2801    TCSS USB3 Port4 Capability for _UPC
  //
  // DTBT1 USB3 Port
  //
  UINT8    Dtbt1Usb3PortGroupPosition[2];           ///< Offset 2802    DTBT1 USB3 Port1 Group Position for _PLD
                                                    ///< Offset 2803    DTBT1 USB3 Port2 Group Position for _PLD
  UINT8    Dtbt1Usb3PortVisibility[2];              ///< Offset 2804    DTBT1 USB3 Port1 Visibility for _PLD
                                                    ///< Offset 2805    DTBT1 USB3 Port2 Visibility for _PLD
  UINT8    Dtbt1Usb3PortConnectable[2];             ///< Offset 2806    DTBT1 USB3 Port1 Connectable for _UPC
                                                    ///< Offset 2807    DTBT1 USB3 Port2 Connectable for _UPC
  UINT8    Dtbt1Usb3PortType[2];                    ///< Offset 2808    DTBT1 USB3 Port1 Type for _UPC
                                                    ///< Offset 2809    DTBT1 USB3 Port2 Type for _UPC
  UINT8    Dtbt1Usb3PortCapability[2];              ///< Offset 2810    DTBT1 USB3 Port1 Capability for _UPC
                                                    ///< Offset 2811    DTBT1 USB3 Port2 Capability for _UPC
  //
  // DTBT2 USB3 Port
  //
  UINT8    Dtbt2Usb3PortGroupPosition[2];           ///< Offset 2812    DTBT2 USB3 Port1 Group Position for _PLD
                                                    ///< Offset 2813    DTBT2 USB3 Port2 Group Position for _PLD
  UINT8    Dtbt2Usb3PortVisibility[2];              ///< Offset 2814    DTBT2 USB3 Port1 Visibility for _PLD
                                                    ///< Offset 2815    DTBT2 USB3 Port2 Visibility for _PLD
  UINT8    Dtbt2Usb3PortConnectable[2];             ///< Offset 2816    DTBT2 USB3 Port1 Connectable for _UPC
                                                    ///< Offset 2817    DTBT2 USB3 Port2 Connectable for _UPC
  UINT8    Dtbt2Usb3PortType[2];                    ///< Offset 2818    DTBT2 USB3 Port1 Type for _UPC
                                                    ///< Offset 2819    DTBT2 USB3 Port2 Type for _UPC
  UINT8    Dtbt2Usb3PortCapability[2];              ///< Offset 2820    DTBT2 USB3 Port1 Capability for _UPC
                                                    ///< Offset 2821    DTBT2 USB3 Port2 Capability for _UPC
  UINT8    TbtRTD3En;                               ///< Offset 2822    DTBT RTD3 enable status (should set to 1 when enable TBT RTD3)
  UINT32   IpfEnable;                               ///< Offset 2823    Ipf Enable
  UINT8    SubBusBoundary;                          ///< Offset 2827    PCI BUS resource occupied boundary
  UINT8    StorageDynamicLinkManagement;            ///< Offset 2828    Storage Dynamic Link (PCIe) Rate management (DLRM) Support
  UINT8    M2Ssd1Gen4_5Dlrm;                        ///< Offset 2829    Pcie slot 1 M.2 SSD Gen4_5 DLRM support
  UINT8    M2Ssd2Gen4_5Dlrm;                        ///< Offset 2830    Pcie slot 2 M.2 SSD Gen4_5 DLRM support
  UINT64   HdaDspPpModCustomGuid4Low;               ///< Offset 2831    HDA PP module custom GUID 4 - first 64bit  [0-63]
  UINT64   HdaDspPpModCustomGuid4High;              ///< Offset 2839    HDA PP module custom GUID 4 - second 64bit [64-127]
  UINT64   HdaDspPpModCustomGuid5Low;               ///< Offset 2847    HDA PP module custom GUID 5 - first 64bit  [0-63]
  UINT64   HdaDspPpModCustomGuid5High;              ///< Offset 2855    HDA PP module custom GUID 5 - second 64bit [64-127]
  UINT8    EVSA;                                    ///< Offset 2863    Everest8326 I2c slave address
  UINT8    RMTE;                                    ///< Offset 2864    RMT/BDAT Enable
  UINT32   I2c0SpeedMode;                           ///< Offset 2865    I2C0 Speed Mode Selection
  UINT32   I2c1SpeedMode;                           ///< Offset 2869    I2C1 Speed Mode Selection
  UINT32   I2c2SpeedMode;                           ///< Offset 2873    I2C2 Speed Mode Selection
  UINT32   I2c3SpeedMode;                           ///< Offset 2877    I2C3 Speed Mode Selection
  UINT32   I2c4SpeedMode;                           ///< Offset 2881    I2C4 Speed Mode Selection
  UINT32   I2c5SpeedMode;                           ///< Offset 2885    I2C5 Speed Mode Selection
} PLATFORM_NVS_AREA;

#pragma pack(pop)
#endif
