//
// Automatically generated by GenNvs ver 2.4.7
// Please DO NOT modify !!!
//


/** @file
  UCSI NVS Area table

  Copyright (c) 2026, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

  // Define a Global region of UCSI NVS Region that may be used for any
  // type of implementation.  The starting offset and size will be fixed
  // up by the System BIOS during POST.  Note that the Size must be a word
  // in size to be fixed up correctly.

#ifndef _UCSI_NVS_AREA_DEF_H_
#define _UCSI_NVS_AREA_DEF_H_

#pragma pack (push,1)
typedef struct {
  UINT32   UcsiOpBaseAddr;                          ///< Offset 0       USB Type C Opregion base address
  UINT16   TypeCPortsMap;                           ///< Offset 4       Connectable Type C ports map
  // UCSI/UCMX Driver Support. 0: Force Disable, 1: UCSI Driver support, 2: UCMX Driver support.
  UINT8    UsbCPort1UcxxSupport;                    ///< Offset 6       Type C Connector 1  UCSI/UCMX Driver Support Enable/ Force Disable.
  UINT8    UsbCPort2UcxxSupport;                    ///< Offset 7       Type C Connector 2  UCSI/UCMX Driver Support Enable/ Force Disable.
  UINT8    UsbCPort3UcxxSupport;                    ///< Offset 8       Type C Connector 3  UCSI/UCMX Driver Support Enable/ Force Disable.
  UINT8    UsbCPort4UcxxSupport;                    ///< Offset 9       Type C Connector 4  UCSI/UCMX Driver Support Enable/ Force Disable.
  UINT8    UsbCPort5UcxxSupport;                    ///< Offset 10      Type C Connector 5  UCSI/UCMX Driver Support Enable/ Force Disable.
  UINT8    UsbCPort6UcxxSupport;                    ///< Offset 11      Type C Connector 6  UCSI/UCMX Driver Support Enable/ Force Disable.
  UINT8    UsbCPort7UcxxSupport;                    ///< Offset 12      Type C Connector 7  UCSI/UCMX Driver Support Enable/ Force Disable.
  UINT8    UsbCPort8UcxxSupport;                    ///< Offset 13      Type C Connector 8  UCSI/UCMX Driver Support Enable/ Force Disable.
  UINT8    UsbCPort9UcxxSupport;                    ///< Offset 14      Type C Connector 9  UCSI/UCMX Driver Support Enable/ Force Disable.
  UINT8    UsbCPortAUcxxSupport;                    ///< Offset 15      Type C Connector A  UCSI/UCMX Driver Support Enable/ Force Disable.
  UINT8    ConnectorGroupPosition[10];              ///< Offset 16      Type-C Connector1 Group Position for _PLD
                                                    ///< Offset 17      Type-C Connector2 Group Position for _PLD
                                                    ///< Offset 18      Type-C Connector3 Group Position for _PLD
                                                    ///< Offset 19      Type-C Connector4 Group Position for _PLD
                                                    ///< Offset 20      Type-C Connector5 Group Position for _PLD
                                                    ///< Offset 21      Type-C Connector6 Group Position for _PLD
                                                    ///< Offset 22      Type-C Connector7 Group Position for _PLD
                                                    ///< Offset 23      Type-C Connector8 Group Position for _PLD
                                                    ///< Offset 24      Type-C Connector9 Group Position for _PLD
                                                    ///< Offset 25      Type-C ConnectorA Group Position for _PLD
  UINT8    ConnectorVisibility[10];                 ///< Offset 26      Type-C Connector1 Visibility for _PLD
                                                    ///< Offset 27      Type-C Connector2 Visibility for _PLD
                                                    ///< Offset 28      Type-C Connector3 Visibility for _PLD
                                                    ///< Offset 29      Type-C Connector4 Visibility for _PLD
                                                    ///< Offset 30      Type-C Connector5 Visibility for _PLD
                                                    ///< Offset 31      Type-C Connector6 Visibility for _PLD
                                                    ///< Offset 32      Type-C Connector7 Visibility for _PLD
                                                    ///< Offset 33      Type-C Connector8 Visibility for _PLD
                                                    ///< Offset 34      Type-C Connector9 Visibility for _PLD
                                                    ///< Offset 35      Type-C ConnectorA Visibility for _PLD
  UINT8    ConnectorConnectable[10];                ///< Offset 36      Type-C Connector1 Connectable for _UPC
                                                    ///< Offset 37      Type-C Connector2 Connectable for _UPC
                                                    ///< Offset 38      Type-C Connector3 Connectable for _UPC
                                                    ///< Offset 39      Type-C Connector4 Connectable for _UPC
                                                    ///< Offset 40      Type-C Connector5 Connectable for _UPC
                                                    ///< Offset 41      Type-C Connector6 Connectable for _UPC
                                                    ///< Offset 42      Type-C Connector7 Connectable for _UPC
                                                    ///< Offset 43      Type-C Connector8 Connectable for _UPC
                                                    ///< Offset 44      Type-C Connector9 Connectable for _UPC
                                                    ///< Offset 45      Type-C ConnectorA Connectable for _UPC
  UINT8    ConnectorType[10];                       ///< Offset 46      Type-C Connector1 Type for _UPC
                                                    ///< Offset 47      Type-C Connector2 Type for _UPC
                                                    ///< Offset 48      Type-C Connector3 Type for _UPC
                                                    ///< Offset 49      Type-C Connector4 Type for _UPC
                                                    ///< Offset 50      Type-C Connector5 Type for _UPC
                                                    ///< Offset 51      Type-C Connector6 Type for _UPC
                                                    ///< Offset 52      Type-C Connector7 Type for _UPC
                                                    ///< Offset 53      Type-C Connector8 Type for _UPC
                                                    ///< Offset 54      Type-C Connector9 Type for _UPC
                                                    ///< Offset 55      Type-C ConnectorA Type for _UPC
  UINT8    ConnectorCapability[10];                 ///< Offset 56      Type-C Connector1 Capability for _UPC
                                                    ///< Offset 57      Type-C Connector2 Capability for _UPC
                                                    ///< Offset 58      Type-C Connector3 Capability for _UPC
                                                    ///< Offset 59      Type-C Connector4 Capability for _UPC
                                                    ///< Offset 60      Type-C Connector5 Capability for _UPC
                                                    ///< Offset 61      Type-C Connector6 Capability for _UPC
                                                    ///< Offset 62      Type-C Connector7 Capability for _UPC
                                                    ///< Offset 63      Type-C Connector8 Capability for _UPC
                                                    ///< Offset 64      Type-C Connector9 Capability for _UPC
                                                    ///< Offset 65      Type-C ConnectorA Capability for _UPC
} UCSI_NVS_AREA;

#pragma pack(pop)
#endif
