/** @file
Defines Platform BoardIds

  Copyright (c) 2024, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent

  This file is automatically generated. Please do NOT modify !!!

**/

#ifndef _PLATFORM_BOARD_ID_H_
#define _PLATFORM_BOARD_ID_H_

#define FlavorMobile                        0x1
#define FlavorDesktop                       0x2
#define FlavorMobileWorkstation             0x6


#define MtlSimicsSkuType 1


#define BoardIdUnknown1                       0xff

// MTL S Board Id's
#define BoardIdMtlSUDimm1DEvcrb               0x21
#define PLATFORM_ID_ARL_S_UDIMM_1DPC_RVP      0x17

//ARL-H Board Id's
#define BoardIdArlhDdr5CRb                    0x1A
#define PLATFORM_ID_ARL_H_DDR5_CRB            0x1A

#define BoardIdArlhDdr5Rvp                    0x3A
#define PLATFORM_ID_ARL_H_DDR5_RVP            0x18

#define BoardIdArlsSodimmRvp                  0x24
#define PLATFORM_ID_ARL_S_SODIMM_RVP          0x15

#endif // _PLATFORM_BOARD_ID_H_
