## @file
#
#  Slim Bootloader CFGDATA Option File.
#
#  Copyright (c) 2021, Intel Corporation. All rights reserved.<BR>
#  SPDX-License-Identifier: BSD-2-Clause-Patent
#
##


- $ACTION      :
    page         : SGX:SEC:"SGX"
- $ACTION      :
    page         : SGX
- SGX_CFG_DATA :
  - !expand { CFGHDR_TMPL : [ SGX_CFG_DATA, 0x330, 0, 0 ] }
  - EnableSgx    :
      name         : Software Guard eXtensions (SGX)
      type         : Combo
      option       : 0:Disabled, 1:Enabled
      help         : >
                     Enable/Disable Software Guard eXtensions (SGX).
      length       : 0x01
      value        : 0x0
  - EpochUpdate  :
      condition    : $(COND_SGX_EN)
      name         : Select Owner EPOCH input type
      type         : Combo
      option       : 0:No Change in Owner EPOCHs, 1:Manual User Defined Owner EPOCHs
      help         : >
                     There are two Owner EPOCH modes (Each EPOCH is 64bit)- no change in owner epoch and manually entered by user. After the user enters epoch values manually, the values will not be visible, for security reasons.
      length       : 0x01
      value        : 0x0
  - SgxEpoch0    :
      condition    : $(COND_SGX_EPOCH_UPD)
      name         : Software Guard eXtensions Epoch 0
      type         : EditNum, HEX, (0x0,0xFFFFFFFFFFFFFFFF)
      length       : 0x8
      value        : 0x553DFD8D5FA48F27
  - SgxEpoch1    :
      condition    : $(COND_SGX_EPOCH_UPD)
      name         : Software Guard eXtensions Epoch 1
      type         : EditNum, HEX, (0x0,0xFFFFFFFFFFFFFFFF)
      length       : 0x8
      value        : 0xD76767B9BE4BFDC1
  - PrmrrSize    :
      condition    : $(COND_SGX_EN)
      name         : PRMRR Size
      type         : Combo
      option       : 0x80000000:2GB, 0x100000000:4GB, 0x200000000:8GB, 0x400000000:16GB, 0x400000000:32GB, 0x800000000:64GB, 0x1000000000:128GB, 0x2000000000:256GB, 0x4000000000:512GB
      help         : >
                     Setting the PRMRR Size
      length       : 0x08
      value        : 0x80000000
  - SgxQos    :
      name         : SGX Qos
      condition    : $(COND_SGX_EN)
      type         : Combo
      option       : 0:Disabled, 1:Enabled
      help         : >
                     Enable/Disable SGX Qos.
      length       : 0x01
      value        : 0x0
  - SgxAutoRegistration    :
      name         : SGX Auto Registration
      condition    : $(COND_SGX_EN)
      type         : Combo
      option       : 0:Disabled, 1:Enabled
      help         : >
                     Enable/Disable Sgx Auto Registration.
      length       : 0x01
      value        : 0x0
  - SgxDebugMode    :
      name         : SGX Debug Mode
      condition    : $(COND_SGX_EN)
      type         : Combo
      option       : 0:Disabled, 1:Enabled
      help         : >
                     Enable/Disable SGX Debug Mode
      length       : 0x01
      value        : 0x0
  - SgxLeWr    :
      name         : SGX Flexible Launch control
      condition    : $(COND_SGX_EN)
      type         : Combo
      option       : 0:Disabled, 1:Enabled
      help         : >
                     Enable/Disable SGX Flexible Launch control
      length       : 0x01
      value        : 0x0
  - SgxLePubKeyHash0    :
      name         : SGX Flexible Launch control Hash 0
      condition    : $(COND_SGX_EN)
      type         : EditNum, HEX, (0x0,0xFFFFFFFFFFFFFFFF)
      help         : >
                     SGX Flexible Launch control Hash 0 value
      length       : 0x08
      value        : 0x0
  - SgxLePubKeyHash1    :
      name         : SGX Flexible Launch control Hash 1
      condition    : $(COND_SGX_EN)
      type         : EditNum, HEX, (0x0,0xFFFFFFFFFFFFFFFF)
      help         : >
                     SGX Flexible Launch control Hash 1 value
      length       : 0x08
      value        : 0x0
  - SgxLePubKeyHash2    :
      name         : SGX Flexible Launch control Hash 2
      condition    : $(COND_SGX_EN)
      type         : EditNum, HEX, (0x0,0xFFFFFFFFFFFFFFFF)
      help         : >
                     SGX Flexible Launch control Hash 2 value
      length       : 0x08
      value        : 0x0
  - SgxLePubKeyHash3    :
      name         : SGX Flexible Launch control Hash 3
      condition    : $(COND_SGX_EN)
      type         : EditNum, HEX, (0x0,0xFFFFFFFFFFFFFFFF)
      help         : >
                     SGX Flexible Launch control Hash 3 value
      length       : 0x08
      value        : 0x0
  - PaddingBytes :
      length       : 0x02
      value        : 0x0

